/**
 * POST /api/reports/generate
 * Generates a monthly AI report for the authenticated user.
 * Body: { year: number, month: number, csvData?: object (premium only) }
 *
 * Data: journal_trades + journal_daily + ai_chart_checks + aura_analysis_trades (Trade Validator)
 * Tone: clinical, harsh-on-behaviour coaching; mandatory negatives; DNA vs monthly split explained.
 */

const { verifyToken } = require('../utils/auth');
const { executeQuery } = require('../db');
const { getPerplexityModelForReports } = require('../ai/perplexity-config');
const { getReportDataSpanDays } = require('./dataSpan');
const { applyScheduledDowngrade } = require('../utils/apply-scheduled-downgrade');
const { effectiveReportsRole } = require('./resolveReportsRole');

const PERPLEXITY_API_KEY = process.env.PERPLEXITY_API_KEY;
const PERPLEXITY_MODEL = getPerplexityModelForReports();
const MIN_DATA_DAYS = 30;

const DISCLAIMER_TEXT =
  'This report is generated by AI from your trading and platform data. It is for educational and self-improvement only. It is not financial, medical, or psychological advice. Feedback addresses trading behaviour and process, not your worth as a person. Past performance does not guarantee future results. If you are in distress, seek a qualified professional.';

function monthName(m) {
  return [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ][m - 1];
}

// ── Data aggregation ──────────────────────────────────────────────────────────

async function aggregateJournalTrades(userId, year, month) {
  const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
  const endDate = new Date(year, month, 0).toISOString().split('T')[0];
  const [rows] = await executeQuery(
    `SELECT pair, tradeType, session, riskPct, rResult, dollarResult,
            followedRules, notes, emotional, date
     FROM journal_trades
     WHERE userId = ? AND date BETWEEN ? AND ?
     ORDER BY date`,
    [userId, startDate, endDate]
  ).catch(() => [[]]);
  return rows || [];
}

/** Trade Validator / Aura Analysis — same window as monthly report */
async function aggregateAuraAnalysisTrades(userId, year, month) {
  const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
  const endDate = new Date(year, month, 0).toISOString().split('T')[0];
  const [rows] = await executeQuery(
    `SELECT pair, session, result, pnl, r_multiple, risk_percent, rr, checklist_percent, created_at
     FROM aura_analysis_trades
     WHERE user_id = ?
       AND result IN ('win','loss','breakeven')
       AND DATE(created_at) BETWEEN ? AND ?
     ORDER BY created_at ASC`,
    [userId, startDate, endDate]
  ).catch(() => [[]]);
  return rows || [];
}

async function aggregateAIChartChecks(userId, year, month) {
  const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
  const endDate = new Date(year, month, 0).toISOString().split('T')[0];
  const [rows] = await executeQuery(
    `SELECT checklist_type, overall_score, status_label, pair, created_at
     FROM ai_chart_checks
     WHERE user_id = ? AND DATE(created_at) BETWEEN ? AND ?`,
    [userId, startDate, endDate]
  ).catch(() => [[]]);
  return rows || [];
}

async function aggregateJournalDaily(userId, year, month) {
  const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
  const endDate = new Date(year, month, 0).toISOString().split('T')[0];
  const [rows] = await executeQuery(
    `SELECT mood, date
     FROM journal_daily
     WHERE userId = ? AND date BETWEEN ? AND ?`,
    [userId, startDate, endDate]
  ).catch(() => [[]]);
  return rows || [];
}

/** Prior calendar month report summary for month-over-month (if exists) */
async function loadPriorReportDigest(userId, year, month) {
  let py = year;
  let pm = month - 1;
  if (pm < 1) {
    pm = 12;
    py -= 1;
  }
  const [rows] = await executeQuery(
    `SELECT content_json, period_year, period_month FROM monthly_reports
     WHERE user_id = ? AND status = 'ready' AND period_year = ? AND period_month = ?
     LIMIT 1`,
    [userId, py, pm]
  ).catch(() => [[]]);
  const row = rows?.[0];
  if (!row?.content_json) return { found: false, periodLabel: `${monthName(pm)} ${py}`, digest: null };
  let c;
  try {
    c = JSON.parse(row.content_json);
  } catch {
    return { found: false, periodLabel: `${monthName(pm)} ${py}`, digest: null };
  }
  const digest = {
    period: c.period,
    executiveSummary: c.executiveSummary || null,
    weakestArea: c.executiveSummary?.weakestArea || null,
    keyFocus: c.executiveSummary?.keyFocus || null,
    performanceHeadline: c.performanceSummary?.headline || null,
    improvementAreas: (c.improvementPlan || []).map((p) => p.area).filter(Boolean),
    failureModesCount: Array.isArray(c.failureModeInventory) ? c.failureModeInventory.length : 0,
  };
  return { found: true, periodLabel: `${monthName(pm)} ${py}`, digest };
}

// ── Metric summaries ──────────────────────────────────────────────────────────

function summariseTrades(trades) {
  if (!trades.length) return null;
  const total = trades.length;
  const wins = trades.filter((t) => (parseFloat(t.rResult) || 0) > 0).length;
  const losses = trades.filter((t) => (parseFloat(t.rResult) || 0) < 0).length;
  const pnlValues = trades.map((t) => parseFloat(t.dollarResult) || 0);
  const totalPnl = pnlValues.reduce((a, b) => a + b, 0);
  const rrValues = trades.map((t) => parseFloat(t.rResult)).filter((v) => !isNaN(v) && v > 0);
  const avgRR = rrValues.length ? (rrValues.reduce((a, b) => a + b, 0) / rrValues.length).toFixed(2) : null;
  const pairs = [...new Set(trades.map((t) => t.pair).filter(Boolean))];
  const sessions = trades.reduce((acc, t) => {
    if (t.session) acc[t.session] = (acc[t.session] || 0) + 1;
    return acc;
  }, {});
  const bestSession = Object.entries(sessions).sort((a, b) => b[1] - a[1])[0]?.[0] || null;
  return {
    source: 'journal_trades',
    total,
    wins,
    losses,
    winRate: total ? Math.round((wins / total) * 100) : 0,
    totalPnl: totalPnl.toFixed(2),
    avgRR,
    topPairs: pairs.slice(0, 5),
    bestSession,
    profitFactor: losses > 0 ? (wins / losses).toFixed(2) : wins > 0 ? '∞' : '0',
  };
}

function summariseValidatorTrades(rows) {
  if (!rows.length) return null;
  const total = rows.length;
  const wins = rows.filter((t) => t.result === 'win').length;
  const losses = rows.filter((t) => t.result === 'loss').length;
  const be = rows.filter((t) => t.result === 'breakeven').length;
  const pnlValues = rows.map((t) => parseFloat(t.pnl) || 0);
  const totalPnl = pnlValues.reduce((a, b) => a + b, 0);
  const rMults = rows
    .filter((t) => t.result === 'win' || t.result === 'loss')
    .map((t) => parseFloat(t.r_multiple))
    .filter((v) => !isNaN(v));
  const avgR = rMults.length ? (rMults.reduce((a, b) => a + b, 0) / rMults.length).toFixed(2) : null;
  const pairs = [...new Set(rows.map((t) => t.pair).filter(Boolean))];
  const sessions = rows.reduce((acc, t) => {
    if (t.session) acc[t.session] = (acc[t.session] || 0) + 1;
    return acc;
  }, {});
  const bestSession = Object.entries(sessions).sort((a, b) => b[1] - a[1])[0]?.[0] || null;
  const checklistVals = rows.map((t) => parseFloat(t.checklist_percent)).filter((v) => !isNaN(v));
  const avgChecklist = checklistVals.length
    ? Math.round(checklistVals.reduce((a, b) => a + b, 0) / checklistVals.length)
    : null;
  const decided = wins + losses;
  return {
    source: 'trade_validator',
    total,
    wins,
    losses,
    breakeven: be,
    winRate: decided ? Math.round((wins / decided) * 100) : 0,
    totalPnl: totalPnl.toFixed(2),
    avgRMultiple: avgR,
    topPairs: pairs.slice(0, 5),
    bestSession,
    avgChecklistPercent: avgChecklist,
    profitFactor: losses > 0 ? (wins / losses).toFixed(2) : wins > 0 ? '∞' : '0',
  };
}

function summariseDiscipline(dailyRows) {
  if (!dailyRows.length) return null;
  const moodMap = { great: 5, good: 4, okay: 3, bad: 2, terrible: 1 };
  const moodVals = dailyRows
    .map((r) => moodMap[(r.mood || '').toLowerCase()])
    .filter((v) => v != null);
  const avgMoodNum = moodVals.length
    ? (moodVals.reduce((a, b) => a + b, 0) / moodVals.length).toFixed(1)
    : null;
  return {
    daysLogged: dailyRows.length,
    avgMood: avgMoodNum,
  };
}

function summariseChartChecks(checks) {
  if (!checks.length) return null;
  const scores = checks.map((c) => c.overall_score || 0);
  const avg = Math.round(scores.reduce((a, b) => a + b, 0) / scores.length);
  const byType = checks.reduce((acc, c) => {
    acc[c.checklist_type] = (acc[c.checklist_type] || 0) + 1;
    return acc;
  }, {});
  return {
    total: checks.length,
    avgScore: avg,
    byType,
    topStatus: checks.sort((a, b) => b.overall_score - a.overall_score)[0]?.status_label || null,
  };
}

function buildFallbackFailureModes({ tradeSummary, validatorSummary, disciplineSummary, chartCheckSummary }) {
  const out = [];
  if (validatorSummary) {
    if (validatorSummary.losses > validatorSummary.wins) {
      out.push(
        `Trade Validator: ${validatorSummary.losses} losses vs ${validatorSummary.wins} wins (${validatorSummary.total} closes) — process or edge is not proven this month.`
      );
    }
    if (validatorSummary.avgChecklistPercent != null && validatorSummary.avgChecklistPercent < 55) {
      out.push(
        `Average checklist completion ~${validatorSummary.avgChecklistPercent}% — sub-50% entries dominate weak execution DNA.`
      );
    }
    if (parseFloat(validatorSummary.totalPnl) < 0) {
      out.push(`Validator P&L is negative (${validatorSummary.totalPnl}) — size or selectivity is failing.`);
    }
  }
  if (tradeSummary && !validatorSummary) {
    if (tradeSummary.losses > tradeSummary.wins) {
      out.push('Journal trades show more losses than wins — same honesty applies: fix process before adding size.');
    }
  }
  if (disciplineSummary && parseFloat(disciplineSummary.avgMood || '3') < 2.5) {
    out.push('Journal mood average is poor — emotional state and trading are coupling; reduce frequency until stable.');
  }
  if (disciplineSummary && disciplineSummary.daysLogged < 8) {
    out.push(`Only ${disciplineSummary.daysLogged} journal days — you are flying blind on discipline.`);
  }
  if (chartCheckSummary && chartCheckSummary.avgScore < 55) {
    out.push(`AI chart checks averaging ${chartCheckSummary.avgScore}% — setup quality is not institutional.`);
  }
  if (out.length < 5) {
    out.push('Absence of a flagged weakness does not mean performance is good — it may mean data is thin or you avoided logging losses.');
    out.push('Retail failure modes to audit: overtrading after boredom, moving stops to avoid loss, revenge entries, oversized recovery trades.');
  }
  return [...new Set(out)].slice(0, 10);
}

function ensureReportShape(parsed, fallbacks) {
  const base = typeof parsed === 'object' && parsed !== null ? parsed : {};
  const fm = Array.isArray(base.failureModeInventory) ? base.failureModeInventory.filter(Boolean) : [];
  const mergedFm = fm.length >= 5 ? fm : [...fm, ...fallbacks.failureModes].slice(0, 10);

  return {
    ...base,
    coverTitle: base.coverTitle || fallbacks.coverTitle,
    traderName: base.traderName || fallbacks.traderName,
    period: base.period || fallbacks.period,
    reportType: base.reportType || fallbacks.reportType,
    generatedDate: base.generatedDate || fallbacks.generatedDate,
    brutalHonesty: base.brutalHonesty || 'Data was insufficient for a full blunt read — log every trade and journal daily.',
    failureModeInventory: mergedFm,
    changeVsPriorMonth:
      base.changeVsPriorMonth || {
        better: ['Prior period not on file or model returned empty — generate reports each month to unlock deltas.'],
        worse: [],
        unchanged: [],
      },
    dnaHandoff:
      base.dnaHandoff ||
      'Trader DNA (/reports/dna) is your 90-day identity mirror: who you are as a trader psychologically and behaviourally. This monthly report is your change playbook: what to fix next, in order. Use DNA for self-knowledge; use this report for execution.',
    improvementPlan: Array.isArray(base.improvementPlan)
      ? base.improvementPlan.map((p) => ({
          ...p,
          measurableCheck:
            p.measurableCheck ||
            'Reconcile at month-end: compare trade count, win rate, and journal days vs this month’s baseline.',
        }))
      : [],
    disclaimer: DISCLAIMER_TEXT,
  };
}

// ── Perplexity report generation ──────────────────────────────────────────────────

async function generateReportContent({
  role,
  user,
  year,
  month,
  tradeSummary,
  validatorSummary,
  disciplineSummary,
  chartCheckSummary,
  csvSummary,
  priorReportDigest,
}) {
  const period = `${monthName(month)} ${year}`;
  const name = user.name || user.username || 'Trader';

  const dataSections = [];

  if (validatorSummary) {
    dataSections.push(`TRADE VALIDATOR (aura_analysis_trades) — primary execution log for Elite / platform-validated trades:
- Closed trades: ${validatorSummary.total} (wins ${validatorSummary.wins}, losses ${validatorSummary.losses}, breakeven ${validatorSummary.breakeven})
- Win rate (excl. BE): ${validatorSummary.winRate}%
- Total P&L: ${validatorSummary.totalPnl}
- Avg R-multiple: ${validatorSummary.avgRMultiple ?? 'N/A'}
- Profit factor (W/L count ratio): ${validatorSummary.profitFactor}
- Avg checklist %: ${validatorSummary.avgChecklistPercent ?? 'N/A'}
- Top pairs: ${validatorSummary.topPairs.join(', ') || 'N/A'}
- Top session: ${validatorSummary.bestSession || 'N/A'}`);
  }

  if (tradeSummary) {
    dataSections.push(`JOURNAL TRADES (journal_trades) — may overlap conceptually with validator; treat as separate log:
- Total: ${tradeSummary.total}, Win rate: ${tradeSummary.winRate}%, P&L: ${tradeSummary.totalPnl}
- Profit factor: ${tradeSummary.profitFactor}, Avg R:R: ${tradeSummary.avgRR || 'N/A'}
- Pairs: ${tradeSummary.topPairs.join(', ') || 'N/A'}, Best session: ${tradeSummary.bestSession || 'N/A'}`);
  }

  if (disciplineSummary) {
    dataSections.push(`DISCIPLINE & JOURNAL METRICS:
- Days Logged: ${disciplineSummary.daysLogged}
- Avg Mood Score: ${disciplineSummary.avgMood ?? 'N/A'} / 5`);
  }

  if (chartCheckSummary) {
    dataSections.push(`AI CHART CHECK ACTIVITY:
- Total Chart Checks: ${chartCheckSummary.total}
- Average Checklist Score: ${chartCheckSummary.avgScore}%
- By Type: ${JSON.stringify(chartCheckSummary.byType)}`);
  }

  if (csvSummary) {
    dataSections.push(`MT5 PERFORMANCE DATA (CSV):
${typeof csvSummary === 'string' ? csvSummary : JSON.stringify(csvSummary, null, 2)}`);
  }

  if (!dataSections.length) {
    dataSections.push('No significant data was found for this period.');
  }

  let priorBlock = 'No prior month report JSON on file.';
  if (priorReportDigest?.found && priorReportDigest.digest) {
    priorBlock = `PRIOR MONTH DIGEST (${priorReportDigest.periodLabel}): ${JSON.stringify(priorReportDigest.digest)}`;
  }

  const systemMessage = `You are a clinical trading performance coach. Your job is developmental, not supportive. Rules:
- Do not flatter. Do not say "great job" unless numbers objectively justify it.
- Every report MUST expose failure modes and self-deception patterns common in retail traders when data hints at them.
- Ground every claim in the numbers provided. If data is thin, say so bluntly — do not invent trades or metrics.
- Harshness applies to trading behaviour and process only — not insults about the person.
- You must output valid JSON only matching the user's schema exactly.
- improvementPlan items MUST include "measurableCheck" — a concrete metric or rule to verify next month.
- failureModeInventory: at least 5 items when any trade or validator data exists; each item must tie to a metric or observable pattern.`;

  const userPrompt = `Generate the monthly development report for "${name}" (${role} plan). Period: ${period}.

${priorBlock}

AVAILABLE DATA:
${dataSections.join('\n\n')}

Return strict JSON only (no markdown). Schema:
{
  "coverTitle": "${period} Monthly Trading Report",
  "traderName": "${name}",
  "period": "${period}",
  "reportType": "${role}",
  "generatedDate": "${new Date().toISOString().split('T')[0]}",
  "brutalHonesty": "<1-3 sentences, zero hedging, cite at least one number if any data exists>",
  "failureModeInventory": ["<specific negative tied to data>", "... at least 5 when trade or validator data exists ..."],
  "changeVsPriorMonth": {
    "better": ["<what improved vs prior digest, or say 'no prior report'>"],
    "worse": ["<what regressed>"],
    "unchanged": ["<what stayed weak>"]
  },
  "dnaHandoff": "<2-4 sentences: DNA = 90-day identity/psychology at /reports/dna; this report = monthly change plan. Tell them to read DNA for who they are and this report for what to do next.>",
  "executiveSummary": {
    "overallAssessment": "<2-3 sentences, blunt>",
    "strongestArea": "<one specific strength or 'none evident from data'>",
    "weakestArea": "<one specific weakness>",
    "keyFocus": "<one measurable focus>"
  },
  "performanceSummary": {
    "headline": "<1 sentence>",
    "keyMetrics": [{"label": "...", "value": "..."}],
    "insights": ["<insight>", "<insight>", "<insight>"]
  },
  "disciplineReview": {
    "headline": "<1 sentence>",
    "patterns": ["<pattern>"],
    "strengths": ["<strength>"],
    "improvements": ["<improvement>"]
  },
  "aiChartCheckReview": {
    "headline": "<1 sentence>",
    "avgAlignment": "<score or N/A>",
    "recurringStrengths": ["<strength>"],
    "recurringGaps": ["<gap>"]
  },
  "mt5Review": ${csvSummary ? `{"headline": "<...>", "insights": ["<...>"]}` : 'null'},
  "improvementPlan": [
    {"area": "<area>", "action": "<step>", "priority": "high|medium|low", "measurableCheck": "<how you know it worked>"},
    {"area": "<area>", "action": "<step>", "priority": "high|medium|low", "measurableCheck": "<...>"},
    {"area": "<area>", "action": "<step>", "priority": "high|medium|low", "measurableCheck": "<...>"}
  ],
  "disclaimer": ${JSON.stringify(DISCLAIMER_TEXT)}
}`;

  const response = await fetch('https://api.perplexity.ai/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${PERPLEXITY_API_KEY}`,
    },
    body: JSON.stringify({
      model: PERPLEXITY_MODEL,
      max_tokens: 4500,
      messages: [
        { role: 'system', content: systemMessage },
        { role: 'user', content: userPrompt },
      ],
    }),
  });

  if (!response.ok) throw new Error(`Perplexity error ${response.status}`);
  const data = await response.json();
  const raw = data.choices?.[0]?.message?.content || '';
  const clean = raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
  let parsed;
  try {
    parsed = JSON.parse(clean);
  } catch {
    throw new Error('Perplexity returned non-JSON');
  }

  const fallbackModes = buildFallbackFailureModes({
    tradeSummary,
    validatorSummary,
    disciplineSummary,
    chartCheckSummary,
  });

  return ensureReportShape(parsed, {
    coverTitle: `${period} Monthly Trading Report`,
    traderName: name,
    period,
    reportType: role,
    generatedDate: new Date().toISOString().split('T')[0],
    failureModes: fallbackModes,
  });
}

// ── Main handler ──────────────────────────────────────────────────────────────

module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', req.headers.origin || '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ success: false, message: 'Method not allowed' });

  if (!PERPLEXITY_API_KEY) return res.status(500).json({ success: false, message: 'AI service not configured' });

  const decoded = verifyToken(req.headers.authorization);
  if (!decoded?.id) return res.status(401).json({ success: false, message: 'Authentication required' });
  const userId = decoded.id;

  const { year, month } = req.body || {};
  if (!year || !month || month < 1 || month > 12) {
    return res.status(400).json({ success: false, message: 'year and month (1–12) are required' });
  }

  try {
    const user = await applyScheduledDowngrade(userId);
    if (!user) return res.status(404).json({ success: false, message: 'User not found' });
    const role = effectiveReportsRole(user);

    if (role === 'free') {
      return res.status(403).json({
        success: false,
        code: 'FREE_PLAN',
        message: 'Monthly AI reports are available on Premium and Elite plans.',
      });
    }

    const dataDays = await getReportDataSpanDays(userId, executeQuery);
    if (dataDays < MIN_DATA_DAYS) {
      return res.status(403).json({
        success: false,
        code: 'INSUFFICIENT_DATA',
        dataDays,
        minDataDays: MIN_DATA_DAYS,
        message: `You need at least ${MIN_DATA_DAYS} days of data to generate a report. You currently have ${dataDays} days.`,
      });
    }

    const [existing] = await executeQuery(
      'SELECT id, status FROM monthly_reports WHERE user_id = ? AND period_year = ? AND period_month = ?',
      [userId, year, month]
    ).catch(() => [[]]);
    if (existing?.[0]?.status === 'ready') {
      return res.status(409).json({
        success: false,
        code: 'ALREADY_EXISTS',
        reportId: existing[0].id,
        message: 'A report for this period already exists.',
      });
    }

    await executeQuery(
      `INSERT INTO monthly_reports (user_id, period_year, period_month, report_type, status)
       VALUES (?, ?, ?, ?, 'generating')
       ON DUPLICATE KEY UPDATE status = 'generating', generated_at = NULL`,
      [userId, year, month, role]
    );

    const [trades, auraRows, dailyEntries, chartChecks, priorReportDigest] = await Promise.all([
      aggregateJournalTrades(userId, year, month),
      aggregateAuraAnalysisTrades(userId, year, month),
      aggregateJournalDaily(userId, year, month),
      aggregateAIChartChecks(userId, year, month),
      loadPriorReportDigest(userId, year, month),
    ]);

    const tradeSummary = summariseTrades(trades);
    const validatorSummary = summariseValidatorTrades(auraRows);
    const disciplineSummary = summariseDiscipline(dailyEntries);
    const chartCheckSummary = summariseChartChecks(chartChecks);

    let csvSummary = null;
    if (role === 'premium') {
      const [csvRows] = await executeQuery(
        'SELECT upload_json FROM report_csv_uploads WHERE user_id = ? AND period_year = ? AND period_month = ?',
        [userId, year, month]
      ).catch(() => [[]]);
      if (csvRows?.[0]?.upload_json) {
        try {
          csvSummary = JSON.parse(csvRows[0].upload_json);
        } catch {
          csvSummary = null;
        }
      }
    }

    const reportContent = await generateReportContent({
      role,
      user,
      year,
      month,
      tradeSummary,
      validatorSummary,
      disciplineSummary,
      chartCheckSummary,
      csvSummary,
      priorReportDigest,
    });

    await executeQuery(
      `UPDATE monthly_reports
       SET status = 'ready', content_json = ?, generated_at = NOW()
       WHERE user_id = ? AND period_year = ? AND period_month = ?`,
      [JSON.stringify(reportContent), userId, year, month]
    );

    return res.status(200).json({ success: true, report: reportContent, year, month });
  } catch (err) {
    console.error('[reports/generate]', err.message);
    await executeQuery(
      `UPDATE monthly_reports SET status = 'failed' WHERE user_id = ? AND period_year = ? AND period_month = ?`,
      [userId, year, month]
    ).catch(() => {});
    return res.status(500).json({ success: false, message: 'Report generation failed. Please try again.' });
  }
};
