/**
 * Trader Deck content API – date-scoped Market Outlook and Market Intelligence.
 * GET ?type=outlook-daily|outlook-weekly|intel-daily|intel-weekly&date=YYYY-MM-DD
 * PUT (admin) body: { type, date, payload } for outlook; intel briefs are managed via brief-upload + list.
 *
 * Intel GET: optional `autogen=1` may trigger background generation when rows are sparse (cron is primary).
 * Default is no autogen on read — avoids regenerating on every page load. When a weekend date has no rows yet, walks back
 * up to five UK weekdays for content; see `briefsSourceDate` and optional `weekendFallback`.
 */

require('../utils/suppress-warnings');

const { executeQuery, addColumnIfNotExists } = require('../db');
const { verifyToken } = require('../utils/auth');
const { DateTime } = require('luxon');
const {
  generateAndStoreInstitutionalBriefOnly,
  generateAndStoreMissingCategoryBriefs,
  isTraderDeskAutomationConfigured,
} = require('./services/autoBriefGenerator');
const {
  isLondonWeekendYmd,
  priorLondonWeekdayYmd,
  getWeekEndingSundayUtcYmd,
} = require('./deskDates');
const {
  DESK_AUTOMATION_CATEGORY_KINDS,
  institutionalBriefKindForPeriod,
  expectedIntelAutomationRowCount,
  isLegacyGeneralBriefKind,
} = require('./deskBriefKinds');

const VALID_TYPES = ['outlook-daily', 'outlook-weekly', 'intel-daily', 'intel-weekly'];
const VALID_PERIODS = ['daily', 'weekly'];

/** Normalize date to YYYY-MM-DD (accepts YYYYMMDD or YYYY-MM-DD). */
function normalizeDate(str) {
  if (!str || typeof str !== 'string') return '';
  const s = str.trim().replace(/\D/g, '');
  if (s.length === 8) return `${s.slice(0, 4)}-${s.slice(4, 6)}-${s.slice(6, 8)}`;
  return str.trim().slice(0, 10);
}

function parseBody(req) {
  if (req.body == null) return {};
  if (typeof req.body === 'object' && !Buffer.isBuffer(req.body)) return req.body;
  try {
    const raw = typeof req.body === 'string' ? req.body : req.body.toString();
    return JSON.parse(raw || '{}');
  } catch {
    return {};
  }
}

async function ensureTables() {
  await executeQuery(`
    CREATE TABLE IF NOT EXISTS trader_deck_outlook (
      id INT AUTO_INCREMENT PRIMARY KEY,
      date DATE NOT NULL,
      period VARCHAR(20) NOT NULL,
      payload JSON NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      UNIQUE KEY uq_date_period (date, period),
      INDEX idx_tdo_date (date)
    )
  `);
  await executeQuery(`
    CREATE TABLE IF NOT EXISTS trader_deck_briefs (
      id INT AUTO_INCREMENT PRIMARY KEY,
      date DATE NOT NULL,
      period VARCHAR(20) NOT NULL,
      title VARCHAR(255) NOT NULL,
      file_url VARCHAR(512) DEFAULT NULL,
      mime_type VARCHAR(128) DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_tdb_date_period (date, period)
    )
  `);
  await addColumnIfNotExists('trader_deck_briefs', 'file_data', 'LONGBLOB DEFAULT NULL');
  await addColumnIfNotExists('trader_deck_briefs', 'brief_kind', "VARCHAR(40) NOT NULL DEFAULT 'general'");
  await addColumnIfNotExists('trader_deck_briefs', 'brief_version', 'INT NOT NULL DEFAULT 1');
  try {
    await executeQuery('CREATE INDEX idx_tdb_date_period_kind_created ON trader_deck_briefs (date, period, brief_kind, created_at)');
  } catch (_) {
    // ignore duplicate-index errors across deployments
  }
}

let ensureTablesPromise = null;
async function ensureTablesOnce() {
  if (!ensureTablesPromise) {
    ensureTablesPromise = ensureTables().catch((err) => {
      ensureTablesPromise = null;
      throw err;
    });
  }
  return ensureTablesPromise;
}

function typeToPeriod(type) {
  if (type === 'outlook-daily' || type === 'intel-daily') return 'daily';
  if (type === 'outlook-weekly' || type === 'intel-weekly') return 'weekly';
  return null;
}

function normalizeStorageDateByType(type, date) {
  const period = typeToPeriod(type);
  if (period === 'weekly') return getWeekEndingSundayUtcYmd(date);
  return date;
}

function periodDateToRunDate(period, dateStr) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(String(dateStr || ''))) return new Date();
  const zone = 'Europe/London';
  if (period === 'weekly') {
    return DateTime.fromISO(`${dateStr}T18:00:00`, { zone }).toJSDate();
  }
  return DateTime.fromISO(`${dateStr}T06:30:00`, { zone }).toJSDate();
}

async function ensureAutoGeneratedBriefsIfMissing({ date, period, autoGenerate = true }) {
  if (!autoGenerate) return;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(String(date || ''))) return;
  if (period !== 'daily' && period !== 'weekly') return;
  if (!isTraderDeckAutomationConfigured()) return;
  const expectedKind = institutionalBriefKindForPeriod(period);
  try {
    const [rows] = await executeQuery(
      `SELECT id FROM trader_deck_briefs WHERE date = ? AND period = ? AND brief_kind = ? LIMIT 1`,
      [date, period, expectedKind]
    );
    if (rows && rows[0]) return;
  } catch (_) {
    /* fall through to generation attempt */
  }
  const runDate = periodDateToRunDate(period, date);
  try {
    await generateAndStoreInstitutionalBriefOnly({
      period,
      runDate,
      timeZone: 'Europe/London',
    });
  } catch (_) {
    // Keep content endpoint resilient even if generation fails.
  }
}

async function ensureAutoGeneratedCategoryBriefsIfMissing({ date, period, autoGenerate = true }) {
  if (!autoGenerate) return;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(String(date || ''))) return;
  if (period !== 'daily' && period !== 'weekly') return;
  if (!isTraderDeckAutomationConfigured()) return;
  try {
    const [rows] = await executeQuery(
      `SELECT DISTINCT COALESCE(LOWER(brief_kind), '') AS brief_kind
       FROM trader_deck_briefs
       WHERE date = ? AND period = ?
         AND COALESCE(LOWER(brief_kind), '') <> 'general'`,
      [date, period]
    );
    const existingKinds = new Set(
      (rows || [])
        .map((r) => String(r?.brief_kind || '').toLowerCase())
        .filter((k) => k && !isLegacyGeneralBriefKind(k))
    );
    const hasAllRequired = DESK_AUTOMATION_CATEGORY_KINDS.every((kind) => existingKinds.has(kind));
    if (hasAllRequired) return;
  } catch (_) {
    // fall through to generation attempt
  }

  const runDate = periodDateToRunDate(period, date);
  try {
    await generateAndStoreMissingCategoryBriefs({
      period,
      runDate,
      timeZone: 'Europe/London',
      isolateOutboundMeter: true,
    });
  } catch (_) {
    // Keep content endpoint resilient even if generation fails.
  }
}

const BRIEF_KIND_ORDER_SQL =
  "CASE COALESCE(LOWER(brief_kind), '') " +
  "WHEN 'aura_institutional_daily' THEN 0 " +
  "WHEN 'aura_institutional_weekly' THEN 0 " +
  "WHEN 'stocks' THEN 2 " +
  "WHEN 'indices' THEN 3 " +
  "WHEN 'futures' THEN 4 " +
  "WHEN 'forex' THEN 5 " +
  "WHEN 'crypto' THEN 6 " +
  "WHEN 'commodities' THEN 7 " +
  "WHEN 'bonds' THEN 8 " +
  "WHEN 'etfs' THEN 9 " +
  "ELSE 99 END";

async function requireAdmin(req) {
  const decoded = verifyToken(req.headers.authorization);
  if (!decoded || !decoded.id) return { ok: false, status: 401, message: 'Authentication required' };
  const [rows] = await executeQuery(
    'SELECT role FROM users WHERE id = ? LIMIT 1',
    [Number(decoded.id)]
  );
  const role = (rows[0]?.role || '').toString().toLowerCase();
  if (role !== 'admin' && role !== 'super_admin') {
    return { ok: false, status: 403, message: 'Admin access required' };
  }
  return { ok: true, decoded };
}

module.exports = async (req, res) => {
  const origin = req.headers.origin || '*';
  res.setHeader('Access-Control-Allow-Origin', origin);
  res.setHeader('Access-Control-Allow-Methods', 'GET, PUT, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') return res.status(200).end();

  try {
    await ensureTablesOnce();
  } catch (err) {
    console.error('Trader deck content ensureTables:', err.message);
    return res.status(500).json({ success: false, message: 'Database error' });
  }

  let url;
  try {
    url = new URL(req.url || '', `http://${req.headers.host || 'localhost'}`);
  } catch (urlErr) {
    return res.status(400).json({ success: false, message: 'Invalid request URL' });
  }
  const queryType = (url.searchParams.get('type') || '').toLowerCase();
  const queryDate = normalizeDate(url.searchParams.get('date') || '');
  /** Explicit opt-in only — cron / admin tools should drive generation; normal UI reads must not stampede the model. */
  const autoGenerate = (url.searchParams.get('autogen') || '0') === '1';

  if (req.method === 'PUT') {
    const body = parseBody(req);
    const putType = (body.type || queryType || '').toLowerCase();
    const putDateRaw = normalizeDate(body.date || queryDate || '');
    if (!VALID_TYPES.includes(putType) || !/^\d{4}-\d{2}-\d{2}$/.test(putDateRaw)) {
      return res.status(400).json({ success: false, message: 'Invalid type or date. Use type=outlook-daily|outlook-weekly|intel-daily|intel-weekly and date=YYYY-MM-DD' });
    }
    const putDate = normalizeStorageDateByType(putType, putDateRaw);
    let admin;
    try {
      admin = await requireAdmin(req);
    } catch (authErr) {
      console.error('Trader deck content requireAdmin:', authErr.message);
      return res.status(500).json({ success: false, message: 'Authentication error' });
    }
    if (!admin.ok) return res.status(admin.status).json({ success: false, message: admin.message });

    if (putType.startsWith('outlook')) {
      const payload = body.payload;
      if (payload === undefined || payload === null) {
        return res.status(400).json({ success: false, message: 'payload required' });
      }
      try {
        const payloadStr = typeof payload === 'string' ? payload : JSON.stringify(payload);
        const putPeriod = typeToPeriod(putType);
        await executeQuery(
          `INSERT INTO trader_deck_outlook (date, period, payload) VALUES (?, ?, ?)
           ON DUPLICATE KEY UPDATE payload = VALUES(payload), updated_at = CURRENT_TIMESTAMP`,
          [putDate, putPeriod, payloadStr]
        );
        return res.status(200).json({ success: true, date: putDate, type: putType });
      } catch (err) {
        console.error('Trader deck content PUT error:', err.message);
        return res.status(500).json({ success: false, message: 'Failed to save outlook' });
      }
    }

    if (putType.startsWith('intel')) {
      return res.status(400).json({ success: false, message: 'Use POST /api/trader-deck/brief-upload to add briefs; DELETE /api/trader-deck/brief to remove.' });
    }
    return res.status(400).json({ success: false, message: 'Invalid type' });
  }

  const type = queryType;
  const dateRaw = queryDate;
  if (!VALID_TYPES.includes(type) || !/^\d{4}-\d{2}-\d{2}$/.test(dateRaw)) {
    return res.status(400).json({ success: false, message: 'Invalid type or date. Use type=outlook-daily|outlook-weekly|intel-daily|intel-weekly and date=YYYY-MM-DD' });
  }
  const date = normalizeStorageDateByType(type, dateRaw);

  const period = typeToPeriod(type);
  const isOutlook = type.startsWith('outlook');
  const isIntel = type.startsWith('intel');

  if (req.method === 'GET') {
    if (isOutlook) {
      const [rows] = await executeQuery(
        'SELECT payload, updated_at FROM trader_deck_outlook WHERE date = ? AND period = ? LIMIT 1',
        [date, period]
      );
      const row = rows[0];
      if (!row) return res.status(200).json({ success: true, payload: null, date, type });
      let payload = row.payload;
      if (typeof payload === 'string') {
        try { payload = JSON.parse(payload); } catch { payload = null; }
      }
      return res.status(200).json({
        success: true,
        payload,
        updatedAt: row.updated_at,
        date,
        type,
      });
    }
    if (isIntel) {
      const readBriefRowsFor = async (day) => {
        const [rowList] = await executeQuery(
          `SELECT id, title, file_url, mime_type, created_at,
                  COALESCE(brief_kind, '') AS brief_kind,
                  COALESCE(brief_version, 1) AS brief_version
           FROM trader_deck_briefs
           WHERE date = ? AND period = ?
             AND COALESCE(LOWER(brief_kind), '') <> 'general'
           ORDER BY ${BRIEF_KIND_ORDER_SQL}, brief_version DESC, created_at DESC`,
          [day, period]
        );
        return Array.isArray(rowList) ? rowList : [];
      };
      let briefsDate = date;
      let rows = await readBriefRowsFor(briefsDate);
      let weekendFallback = false;
      if (period === 'daily' && isLondonWeekendYmd(date) && rows.length === 0) {
        weekendFallback = true;
        let probe = priorLondonWeekdayYmd(date);
        let found = null;
        for (let step = 0; step < 5; step++) {
          const tryRows = await readBriefRowsFor(probe);
          if (tryRows.length > 0) {
            found = { day: probe, rows: tryRows };
            break;
          }
          probe = priorLondonWeekdayYmd(probe);
        }
        if (found) {
          briefsDate = found.day;
          rows = found.rows;
        } else {
          briefsDate = priorLondonWeekdayYmd(date);
          rows = await readBriefRowsFor(briefsDate);
        }
      }

      const autogenAnchor = briefsDate;
      const expectedRows = expectedIntelAutomationRowCount();
      if (rows.length < expectedRows && autoGenerate) {
        // Serial runs reduce DB/API stampedes vs parallel institutional + category jobs.
        // Never block this endpoint on generation; backfill in the background.
        Promise.resolve()
          .then(() => ensureAutoGeneratedBriefsIfMissing({ date: autogenAnchor, period, autoGenerate: true }))
          .then(() => ensureAutoGeneratedCategoryBriefsIfMissing({ date: autogenAnchor, period, autoGenerate: true }))
          .catch(() => {});
      }
      const briefs = (rows || []).map((r) => ({
        id: r.id,
        title: r.title || 'Brief',
        briefKind: String(r.brief_kind || '').toLowerCase(),
        briefVersion: Number(r.brief_version || 1),
        previewUrl: r.file_url ? null : `/api/trader-deck/brief-preview?id=${r.id}`,
        fileUrl: r.file_url || null,
        mimeType: r.mime_type || null,
        createdAt: r.created_at,
      }));
      const payload = {
        success: true,
        briefs,
        date,
        type,
        briefsSourceDate: briefsDate,
      };
      if (weekendFallback) payload.weekendFallback = true;
      return res.status(200).json(payload);
    }
    return res.status(400).json({ success: false, message: 'Invalid type' });
  }

  return res.status(405).json({ success: false, message: 'Method not allowed' });
};
