/**
 * Asset metadata for Aura Analysis (display list, dropdown).
 * Single source of truth: forex, metals, commodities, energy, indices, stocks, futures, crypto.
 */

function f(symbol, displayName, assetClass, distanceType, pipMultiplier, pricePrecision, quantityPrecision, contractSizeHint, pipValueHint, quoteType) {
  return {
    symbol,
    displayName,
    assetClass,
    distanceType,
    pipMultiplier,
    pricePrecision,
    quantityPrecision,
    contractSizeHint,
    pipValueHint,
    quoteType,
  };
}

function stockAsset(symbol, displayName) {
  return f(symbol, displayName, 'stocks', 'point', 1, 2, 2, null, 1, 'USD');
}

const ASSETS = [
  { symbol: 'EURUSD', displayName: 'EUR/USD', assetClass: 'forex', distanceType: 'pip', pipMultiplier: 10000, pricePrecision: 5, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'USD' },
  { symbol: 'GBPUSD', displayName: 'GBP/USD', assetClass: 'forex', distanceType: 'pip', pipMultiplier: 10000, pricePrecision: 5, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'USD' },
  { symbol: 'USDJPY', displayName: 'USD/JPY', assetClass: 'forex', distanceType: 'pip', pipMultiplier: 100, pricePrecision: 3, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'JPY' },
  { symbol: 'USDCHF', displayName: 'USD/CHF', assetClass: 'forex', distanceType: 'pip', pipMultiplier: 10000, pricePrecision: 5, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'CHF' },
  { symbol: 'USDCAD', displayName: 'USD/CAD', assetClass: 'forex', distanceType: 'pip', pipMultiplier: 10000, pricePrecision: 5, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'USD' },
  { symbol: 'AUDUSD', displayName: 'AUD/USD', assetClass: 'forex', distanceType: 'pip', pipMultiplier: 10000, pricePrecision: 5, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'USD' },
  { symbol: 'NZDUSD', displayName: 'NZD/USD', assetClass: 'forex', distanceType: 'pip', pipMultiplier: 10000, pricePrecision: 5, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'USD' },
  { symbol: 'EURGBP', displayName: 'EUR/GBP', assetClass: 'forex', distanceType: 'pip', pipMultiplier: 10000, pricePrecision: 5, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'GBP' },
  { symbol: 'EURJPY', displayName: 'EUR/JPY', assetClass: 'forex', distanceType: 'pip', pipMultiplier: 100, pricePrecision: 3, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'JPY' },
  { symbol: 'GBPJPY', displayName: 'GBP/JPY', assetClass: 'forex', distanceType: 'pip', pipMultiplier: 100, pricePrecision: 3, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'JPY' },
  { symbol: 'XAUUSD', displayName: 'XAU/USD (Gold)', assetClass: 'metals', distanceType: 'point', pipMultiplier: 10, pricePrecision: 2, quantityPrecision: 2, contractSizeHint: 100, pipValueHint: 1, quoteType: 'USD' },
  { symbol: 'XAGUSD', displayName: 'XAG/USD (Silver)', assetClass: 'metals', distanceType: 'point', pipMultiplier: 100, pricePrecision: 3, quantityPrecision: 2, contractSizeHint: 5000, pipValueHint: 0.5, quoteType: 'USD' },
  { symbol: 'XTIUSD', displayName: 'WTI Crude Oil', assetClass: 'energy', distanceType: 'point', pipMultiplier: 100, pricePrecision: 2, quantityPrecision: 2, contractSizeHint: null, pipValueHint: 10, quoteType: 'USD' },
  { symbol: 'XBRUSD', displayName: 'Brent Crude Oil', assetClass: 'energy', distanceType: 'point', pipMultiplier: 100, pricePrecision: 2, quantityPrecision: 2, contractSizeHint: null, pipValueHint: 10, quoteType: 'USD' },
  { symbol: 'US30', displayName: 'US30 (Dow)', assetClass: 'indices', distanceType: 'point', pipMultiplier: 1, pricePrecision: 0, quantityPrecision: 2, contractSizeHint: null, pipValueHint: 1, quoteType: 'USD' },
  { symbol: 'NAS100', displayName: 'NAS100 (Nasdaq)', assetClass: 'indices', distanceType: 'point', pipMultiplier: 1, pricePrecision: 0, quantityPrecision: 2, contractSizeHint: null, pipValueHint: 1, quoteType: 'USD' },
  { symbol: 'SPX500', displayName: 'SPX500 (S&P 500)', assetClass: 'indices', distanceType: 'point', pipMultiplier: 1, pricePrecision: 0, quantityPrecision: 2, contractSizeHint: null, pipValueHint: 1, quoteType: 'USD' },
  { symbol: 'GER40', displayName: 'GER40 (DAX)', assetClass: 'indices', distanceType: 'point', pipMultiplier: 1, pricePrecision: 0, quantityPrecision: 2, contractSizeHint: null, pipValueHint: 1, quoteType: 'USD' },
  stockAsset('AAPL', 'Apple'),
  stockAsset('TSLA', 'Tesla'),
  stockAsset('NVDA', 'NVIDIA'),
  stockAsset('V', 'Visa'),
  stockAsset('AXP', 'American Express'),
  stockAsset('BLK', 'BlackRock'),
  stockAsset('GS', 'Goldman Sachs'),
  stockAsset('MS', 'Morgan Stanley'),
  stockAsset('BX', 'Blackstone'),
  stockAsset('KKR', 'KKR'),
  stockAsset('ICE', 'Intercontinental Exchange'),
  stockAsset('PGR', 'Progressive'),
  stockAsset('CB', 'Chubb'),
  stockAsset('MMC', 'Marsh McLennan'),
  stockAsset('AON', 'Aon'),
  stockAsset('JNJ', 'Johnson & Johnson'),
  stockAsset('ABBV', 'AbbVie'),
  stockAsset('ABT', 'Abbott Laboratories'),
  stockAsset('DHR', 'Danaher'),
  stockAsset('BSX', 'Boston Scientific'),
  stockAsset('SYK', 'Stryker'),
  stockAsset('ELV', 'Elevance Health'),
  stockAsset('CI', 'Cigna'),
  stockAsset('LLY', 'Eli Lilly'),
  stockAsset('GEV', 'GE Vernova'),
  stockAsset('RTX', 'RTX'),
  stockAsset('LMT', 'Lockheed Martin'),
  stockAsset('NOC', 'Northrop Grumman'),
  stockAsset('GD', 'General Dynamics'),
  stockAsset('EMR', 'Emerson Electric'),
  stockAsset('ETN', 'Eaton'),
  stockAsset('PH', 'Parker-Hannifin'),
  stockAsset('TT', 'Trane Technologies'),
  stockAsset('WM', 'Waste Management'),
  stockAsset('WCN', 'Waste Connections'),
  stockAsset('URI', 'United Rentals'),
  stockAsset('PCAR', 'PACCAR'),
  stockAsset('TTC', 'Toro'),
  stockAsset('ITW', 'Illinois Tool Works'),
  stockAsset('XOM', 'Exxon Mobil'),
  stockAsset('CVX', 'Chevron'),
  stockAsset('SLB', 'Schlumberger'),
  stockAsset('HAL', 'Halliburton'),
  stockAsset('OKE', 'ONEOK'),
  stockAsset('KMI', 'Kinder Morgan'),
  stockAsset('WMB', 'Williams'),
  stockAsset('VST', 'Vistra'),
  stockAsset('CEG', 'Constellation Energy'),
  stockAsset('NEE', 'NextEra Energy'),
  stockAsset('DUK', 'Duke Energy'),
  stockAsset('SO', 'Southern Company'),
  stockAsset('AEP', 'American Electric Power'),
  stockAsset('MCD', 'McDonald\'s'),
  stockAsset('NKE', 'Nike'),
  stockAsset('SBUX', 'Starbucks'),
  stockAsset('RCL', 'Royal Caribbean'),
  stockAsset('HLT', 'Hilton'),
  stockAsset('MAR', 'Marriott'),
  stockAsset('CMG', 'Chipotle'),
  stockAsset('YUM', 'Yum! Brands'),
  stockAsset('DPZ', 'Domino\'s'),
  stockAsset('EL', 'Estee Lauder'),
  stockAsset('TPR', 'Tapestry'),
  stockAsset('RL', 'Ralph Lauren'),
  stockAsset('DECK', 'Deckers'),
  stockAsset('TMUS', 'T-Mobile US'),
  stockAsset('T', 'AT&T'),
  stockAsset('VZ', 'Verizon'),
  stockAsset('SPOT', 'Spotify'),
  stockAsset('RDDT', 'Reddit'),
  stockAsset('TTD', 'Trade Desk'),
  stockAsset('TPL', 'Texas Pacific Land'),
  stockAsset('RSG', 'Republic Services'),
  stockAsset('APO', 'Apollo Global Management'),
  stockAsset('CARR', 'Carrier'),
  stockAsset('OTIS', 'Otis'),
  stockAsset('FERG', 'Ferguson'),
  stockAsset('HWM', 'Howmet Aerospace'),
  stockAsset('SPY', 'SPDR S&P 500 ETF'),
  stockAsset('VOO', 'Vanguard S&P 500 ETF'),
  stockAsset('IVV', 'iShares Core S&P 500 ETF'),
  stockAsset('QQQ', 'Invesco QQQ Trust'),
  stockAsset('VTI', 'Vanguard Total Stock Market ETF'),
  stockAsset('SCHB', 'Schwab U.S. Broad Market ETF'),
  stockAsset('DIA', 'SPDR Dow Jones Industrial Average ETF'),
  stockAsset('SCHG', 'Schwab U.S. Large-Cap Growth ETF'),
  stockAsset('VUG', 'Vanguard Growth ETF'),
  stockAsset('MGK', 'Vanguard Mega Cap Growth ETF'),
  stockAsset('IWF', 'iShares Russell 1000 Growth ETF'),
  stockAsset('SPYG', 'SPDR Portfolio S&P 500 Growth ETF'),
  stockAsset('VGT', 'Vanguard Information Technology ETF'),
  stockAsset('XLK', 'Technology Select Sector SPDR'),
  stockAsset('IYW', 'iShares U.S. Technology ETF'),
  stockAsset('FTEC', 'Fidelity MSCI Information Technology ETF'),
  stockAsset('AIQ', 'Global X Artificial Intelligence & Technology ETF'),
  stockAsset('BOTZ', 'Global X Robotics & Artificial Intelligence ETF'),
  stockAsset('ROBO', 'ROBO Global Robotics & Automation ETF'),
  stockAsset('SMH', 'VanEck Semiconductor ETF'),
  stockAsset('SOXX', 'iShares Semiconductor ETF'),
  stockAsset('XSD', 'SPDR S&P Semiconductor ETF'),
  stockAsset('PSI', 'Invesco Dynamic Semiconductors ETF'),
  stockAsset('XLF', 'Financial Select Sector SPDR'),
  stockAsset('VFH', 'Vanguard Financials ETF'),
  stockAsset('IYF', 'iShares U.S. Financials ETF'),
  stockAsset('KBE', 'SPDR S&P Bank ETF'),
  stockAsset('KRE', 'SPDR S&P Regional Banking ETF'),
  stockAsset('IAI', 'iShares U.S. Broker-Dealers & Securities Exchanges ETF'),
  stockAsset('XLV', 'Health Care Select Sector SPDR'),
  stockAsset('VHT', 'Vanguard Health Care ETF'),
  stockAsset('IYH', 'iShares U.S. Healthcare ETF'),
  stockAsset('XBI', 'SPDR S&P Biotech ETF'),
  stockAsset('IHI', 'iShares U.S. Medical Devices ETF'),
  stockAsset('XLI', 'Industrial Select Sector SPDR'),
  stockAsset('VIS', 'Vanguard Industrials ETF'),
  stockAsset('PAVE', 'Global X U.S. Infrastructure Development ETF'),
  stockAsset('IFRA', 'iShares U.S. Infrastructure ETF'),
  stockAsset('GRID', 'First Trust NASDAQ Clean Edge Smart Grid Infrastructure ETF'),
  stockAsset('ITA', 'iShares U.S. Aerospace & Defense ETF'),
  stockAsset('XAR', 'SPDR S&P Aerospace & Defense ETF'),
  stockAsset('PPA', 'Invesco Aerospace & Defense ETF'),
  stockAsset('XLE', 'Energy Select Sector SPDR'),
  stockAsset('VDE', 'Vanguard Energy ETF'),
  stockAsset('IYE', 'iShares U.S. Energy ETF'),
  stockAsset('MLPX', 'Global X MLP & Energy Infrastructure ETF'),
  stockAsset('AMLP', 'Alerian MLP ETF'),
  stockAsset('XLU', 'Utilities Select Sector SPDR'),
  stockAsset('VPU', 'Vanguard Utilities ETF'),
  stockAsset('IDU', 'iShares U.S. Utilities ETF'),
  stockAsset('UTES', 'Virtus Reaves Utilities ETF'),
  stockAsset('XLY', 'Consumer Discretionary Select Sector SPDR'),
  stockAsset('VCR', 'Vanguard Consumer Discretionary ETF'),
  stockAsset('XLP', 'Consumer Staples Select Sector SPDR'),
  stockAsset('VDC', 'Vanguard Consumer Staples ETF'),
  stockAsset('PEJ', 'Invesco Leisure & Entertainment ETF'),
  stockAsset('QUAL', 'iShares MSCI USA Quality Factor ETF'),
  stockAsset('SPHQ', 'Invesco S&P 500 Quality ETF'),
  stockAsset('SCHD', 'Schwab U.S. Dividend Equity ETF'),
  stockAsset('DGRO', 'iShares Core Dividend Growth ETF'),
  stockAsset('VIG', 'Vanguard Dividend Appreciation ETF'),
  stockAsset('NOBL', 'ProShares S&P 500 Dividend Aristocrats ETF'),
  { symbol: 'ES', displayName: 'E-mini S&P 500', assetClass: 'futures', distanceType: 'point', pipMultiplier: 1, pricePrecision: 2, quantityPrecision: 2, contractSizeHint: null, pipValueHint: 50, quoteType: 'USD' },
  { symbol: 'NQ', displayName: 'E-mini Nasdaq', assetClass: 'futures', distanceType: 'point', pipMultiplier: 1, pricePrecision: 2, quantityPrecision: 2, contractSizeHint: null, pipValueHint: 20, quoteType: 'USD' },
  { symbol: 'GC', displayName: 'Gold', assetClass: 'futures', distanceType: 'point', pipMultiplier: 10, pricePrecision: 2, quantityPrecision: 2, contractSizeHint: null, pipValueHint: 100, quoteType: 'USD' },
  { symbol: 'CL', displayName: 'Crude Oil WTI', assetClass: 'futures', distanceType: 'point', pipMultiplier: 100, pricePrecision: 2, quantityPrecision: 2, contractSizeHint: null, pipValueHint: 1000, quoteType: 'USD' },
  { symbol: 'BTCUSD', displayName: 'BTC/USD', assetClass: 'crypto', distanceType: 'price', pipMultiplier: 1, pricePrecision: 2, quantityPrecision: 4, contractSizeHint: null, pipValueHint: 1, quoteType: 'USD' },
  { symbol: 'ETHUSD', displayName: 'ETH/USD', assetClass: 'crypto', distanceType: 'price', pipMultiplier: 1, pricePrecision: 2, quantityPrecision: 4, contractSizeHint: null, pipValueHint: 1, quoteType: 'USD' },
];

const bySymbol = new Map();
ASSETS.forEach((a) => bySymbol.set(a.symbol.toUpperCase(), a));

export const ASSET_CLASS_ORDER = ['forex', 'metals', 'commodity', 'energy', 'indices', 'stocks', 'futures', 'crypto'];

export const ASSET_CLASS_LABELS = {
  forex: 'Forex',
  metals: 'Metals',
  commodity: 'Commodities',
  energy: 'Energy',
  indices: 'Indices',
  stocks: 'Stocks',
  futures: 'Futures',
  crypto: 'Crypto',
};

export function getAssetMetadata(symbol) {
  const upper = String(symbol).toUpperCase();
  const known = bySymbol.get(upper);
  if (known) return known;
  const fallback = ASSETS[0];
  return fallback ? { ...fallback, symbol: upper, displayName: upper } : { symbol: upper, displayName: upper, assetClass: 'forex', distanceType: 'pip', pipMultiplier: 10000, pricePrecision: 5, quantityPrecision: 2, contractSizeHint: 100000, pipValueHint: 10, quoteType: 'USD' };
}

export function getAllAssetMetadata() {
  return [...ASSETS];
}

export function getAssetsByClass() {
  const map = new Map();
  for (const cls of ASSET_CLASS_ORDER) {
    map.set(cls, ASSETS.filter((a) => a.assetClass === cls));
  }
  return map;
}
