/**
 * One-off: builds scripts/i18n-part6.mjs — run: node scripts/_emit-part6.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LANGS = ['en', 'zh-CN', 'hi', 'es', 'fr', 'ar', 'bn', 'pt', 'ru', 'ur'];

function seed(key, en, z, h, e, f, a, b, p, r, u) {
  const row = { k: key, en };
  row['zh-CN'] = z;
  row.hi = h;
  row.es = e;
  row.fr = f;
  row.ar = a;
  row.bn = b;
  row.pt = p;
  row.ru = r;
  row.ur = u;
  return row;
}

const rows = [
  seed('community.date.today', 'Today', '今天', 'आज', 'Hoy', "Aujourd'hui", 'اليوم', 'আজ', 'Hoje', 'Сегодня', 'آج'),
  seed('community.date.yesterday', 'Yesterday', '昨天', 'कल', 'Ayer', 'Hier', 'أمس', 'গতকাল', 'Ontem', 'Вчера', 'کل'),
  seed('community.category.elite', 'Elite', '精英', 'एलीट', 'Élite', 'Élite', 'نخبة', 'এলিট', 'Elite', 'Элита', 'ایلیٹ'),
  seed('community.category.announcements', 'ANNOUNCEMENTS', '公告', 'घोषणाएँ', 'ANUNCIOS', 'ANNONCES', 'إعلانات', 'ঘোষণা', 'AVISOS', 'ОБЪЯВЛЕНИЯ', 'اعلانات'),
  seed('community.category.staff', 'STAFF', '工作人员', 'स्टाफ', 'PERSONAL', 'ÉQUIPE', 'الطاقم', 'স্টাফ', 'EQUIPE', 'ПЕРСОНАЛ', 'اسٹاف'),
  seed('community.category.forums', 'FORUMS', '论坛', 'फ़ोरम', 'FOROS', 'FORUMS', 'المنتديات', 'ফোরাম', 'FÓRUNS', 'ФОРУМЫ', 'فورمز'),
  seed('community.category.trading', 'TRADING', '交易', 'ट्रेडिंग', 'TRADING', 'TRADING', 'التداول', 'ট্রেডিং', 'TRADING', 'ТРЕЙДИНГ', 'ٹریڈنگ'),
  seed('community.category.general', 'GENERAL', '综合', 'सामान्य', 'GENERAL', 'GÉNÉRAL', 'عام', 'সাধারণ', 'GERAL', 'ОБЩЕЕ', 'عمومی'),
  seed('community.category.support', 'SUPPORT', '支持', 'सहायता', 'SOPORTE', 'ASSISTANCE', 'الدعم', 'সাপোর্ট', 'SUPORTE', 'ПОДДЕРЖКА', 'سپورٹ'),
  seed('community.category.premium', 'PRO', '专业版', 'प्रो', 'PRO', 'PRO', 'احترافي', 'প্রো', 'PRO', 'PRO', 'پرو'),
  seed('community.role.member', 'Member', '成员', 'सदस्य', 'Miembro', 'Membre', 'عضو', 'সদস্য', 'Membro', 'Участник', 'رکن'),
  seed('community.time.unknownTime', 'Unknown time', '未知时间', 'अज्ञात समय', 'Hora desconocida', 'Heure inconnue', 'وقت غير معروف', 'অজানা সময়', 'Hora desconhecida', 'Неизвестное время', 'نامعلوم وقت'),
  seed('community.time.invalidDate', 'Invalid date', '无效日期', 'अमान्य तिथि', 'Fecha no válida', 'Date invalide', 'تاريخ غير صالح', 'অবৈধ তারিখ', 'Data inválida', 'Неверная дата', 'غلط تاریخ'),
  seed('community.time.justNow', 'Just now', '刚刚', 'अभी', 'Ahora mismo', "À l'instant", 'الآن', 'এইমাত্র', 'Agora mesmo', 'Только что', 'ابھی'),
  seed('community.time.minutesAgo', '{{count}}m ago', '{{count}} 分钟前', '{{count}} मि पहले', 'hace {{count}} min', 'il y a {{count}} min', 'منذ {{count}} د', '{{count}} মি আগে', 'há {{count}} min', '{{count}} мин назад', '{{count}} منٹ پہلے'),
  seed('community.time.hoursAgo', '{{count}}h ago', '{{count}} 小时前', '{{count}} घंटे पहले', 'hace {{count}} h', 'il y a {{count}} h', 'منذ {{count}} س', '{{count}} ঘ আগে', 'há {{count}} h', '{{count}} ч назад', '{{count}} گھ پہلے'),
  seed('community.time.daysAgo', '{{count}}d ago', '{{count}} 天前', '{{count}} दिन पहले', 'hace {{count}} d', 'il y a {{count}} j', 'منذ {{count}} يوم', '{{count}} দিন আগে', 'há {{count}} d', '{{count}} дн назад', '{{count}} دن پہلے'),
  seed('community.time.yesterdayAt', 'Yesterday at {{time}}', '昨天 {{time}}', 'कल {{time}}', 'Ayer a las {{time}}', 'Hier à {{time}}', 'أمس في {{time}}', 'গতকাল {{time}}', 'Ontem às {{time}}', 'Вчера в {{time}}', 'کل {{time}}'),
  seed('community.toast.passportExpired', 'Trader Passport attachment expired — generate a new one from The Operator → Trader CV.', '交易者护照附件已过期——请在 The Operator → Trader CV 重新生成。', 'ट्रेडर पासपोर्ट समाप्त — The Operator → Trader CV से नया बनाएँ।', 'El adjunto del Trader Passport caducó; genérelo de nuevo en The Operator → Trader CV.', 'Le passeport trader a expiré — régénérez-le dans The Operator → Trader CV.', 'انتهت صلاحية مرفق جواز المتداول — أنشئه من The Operator → Trader CV.', 'ট্রেডার পাসপোর্ট মেয়াদ শেষ — The Operator → Trader CV থেকে নতুন তৈরি করুন।', 'Anexo do Trader Passport expirou — gere de novo em The Operator → Trader CV.', 'Вложение Trader Passport истекло — создайте заново в The Operator → Trader CV.', 'ٹریڈر پاسپورٹ کی میعاد ختم — The Operator → Trader CV سے نیا بنائیں۔'),
  seed('community.toast.passportAttached', 'Trader Passport attached — pick a channel and send. Only people in that channel will see it.', '已附加交易者护照——选择频道并发送。仅该频道内的人可见。', 'ट्रेडर पासपोर्ट जोड़ा गया — चैनल चुनें और भेजें। केवल उस चैनल में लोग देखेंगे।', 'Trader Passport adjunto: elige un canal y envía. Solo lo verán quienes estén en ese canal.', 'Trader Passport joint — choisissez un canal et envoyez. Seuls les membres du canal le verront.', 'تم إرفاق جواز المتداول — اختر قناة وأرسل. يراه فقط من في تلك القناة.', 'ট্রেডার পাসপোর্ট সংযুক্ত — চ্যানেল বেছে পাঠান। শুধু সেই চ্যানেলের লোক দেখবে।', 'Trader Passport anexado — escolha um canal e envie. Só quem está no canal verá.', 'Trader Passport прикреплён — выберите канал и отправьте. Увидят только участники канала.', 'ٹریڈر پاسپورٹ منسلک — چینل منتخب کریں بھیجیں۔ صرف وہاں کے لوگ دیکھیں گے۔'),
  seed('community.toast.passportAttachFailed', 'Could not attach Trader Passport. Use Save on Trader CV and upload the image manually.', '无法附加交易者护照。请在 Trader CV 保存并手动上传图片。', 'ट्रेडर पासपोर्ट नहीं जोड़ा जा सका। Trader CV पर Save कर मैन्युअल अपलोड करें।', 'No se pudo adjuntar el Trader Passport. Guarde en Trader CV y suba la imagen manualmente.', 'Impossible de joindre le Trader Passport. Enregistrez dans Trader CV et téléversez l’image.', 'تعذر إرفاق جواز المتداول. احفظ في Trader CV وارفع الصورة يدويًا.', 'ট্রেডার পাসপোর্ট সংযুক্ত করা যায়নি। Trader CV-এ Save করে ম্যানুয়ালি আপলোড করুন।', 'Não foi possível anexar o Trader Passport. Salve no Trader CV e envie a imagem manualmente.', 'Не удалось прикрепить Trader Passport. Сохраните в Trader CV и загрузите вручную.', 'ٹریڈر پاسپورٹ منسلک نہیں ہوا۔ Trader CV پر محفوظ کریں اور دستی اپ لوڈ کریں۔'),
  seed('community.toast.categoryDeleted', 'Category deleted successfully', '分类已删除', 'श्रेणी हटाई गई', 'Categoría eliminada', 'Catégorie supprimée', 'تم حذف الفئة', 'ক্যাটাগরি মুছে ফেলা হয়েছে', 'Categoria excluída', 'Категория удалена', 'زمرہ حذف ہو گیا'),
  seed('community.toast.categoryRenamed', 'Category renamed successfully', '分类已重命名', 'श्रेणी का नाम बदला गया', 'Categoría renombrada', 'Catégorie renommée', 'تمت إعادة تسمية الفئة', 'ক্যাটাগরির নাম পরিবর্তন', 'Categoria renomeada', 'Категория переименована', 'زمرے کا نام بدلا گیا'),
  seed('community.toast.downloadFailed', 'Download failed. The file data may be corrupted.', '下载失败。文件可能已损坏。', 'डाउनलोड विफल। फ़ाइल खराब हो सकती है।', 'Error al descargar. Los datos pueden estar corruptos.', 'Échec du téléchargement. Données peut-être corrompues.', 'فشل التنزيل. قد تكون البيانات تالفة।', 'ডাউনলোড ব্যর্থ। ফাইল নষ্ট হতে পারে।', 'Falha no download. Dados podem estar corrompidos.', 'Сбой загрузки. Данные могут быть повреждены.', 'ڈاؤن لوڈ ناکام۔ فائل خراب ہو سکتی ہے۔'),
  seed('community.msg.saveFailed', 'Message could not be saved. Try again in a moment.', '消息无法保存。请稍后重试。', 'संदेश सहेजा नहीं जा सका। क्षण बाद पुनः प्रयास करें।', 'No se pudo guardar el mensaje. Inténtalo en un momento.', "Le message n'a pas pu être enregistré. Réessayez.", 'تعذر حفظ الرسالة. أعد المحاولة لاحقًا.', 'বার্তা সংরক্ষণ হয়নি। একটু পরে চেষ্টা করুন।', 'Não foi possível salvar a mensagem. Tente em instantes.', 'Сообщение не сохранилось. Повторите позже.', 'پیغام محفوظ نہیں ہوا۔ دوبارہ کوشش کریں۔'),
  seed('community.toast.sendFailed', 'Failed to send message. Please try again.', '发送消息失败，请重试。', 'संदेश नहीं भेजा जा सका।', 'No se pudo enviar el mensaje.', "Échec de l'envoi du message.", 'فشل إرسال الرسالة.', 'বার্তা পাঠাতে ব্যর্থ।', 'Falha ao enviar mensagem.', 'Не удалось отправить сообщение.', 'پیغام بھیجنے میں ناکامی۔'),
  seed('community.toast.acceptFailed', 'Failed to accept. Please try again.', '接受失败，请重试。', 'स्वीकार नहीं हो सका।', 'No se pudo aceptar.', "Échec de l'acceptation.", 'فشل القبول.', 'গ্রহণ ব্যর্থ।', 'Falha ao aceitar.', 'Не удалось принять.', 'قبول ناکام۔'),
  seed('community.toast.channelNotifFailed', 'Could not update channel notifications', '无法更新频道通知', 'चैनल सूचनाएँ अपडेट नहीं हुईं', 'No se pudieron actualizar las notificaciones del canal', 'Impossible de mettre à jour les notifications du canal', 'تعذر تحديث إشعارات القناة', 'চ্যানেল নোটিফিকেশন আপডেট হয়নি', 'Não foi possível atualizar notificações do canal', 'Не удалось обновить уведомления канала', 'چینل نوٹیفیکیشن اپ ڈیٹ نہیں ہو سکیں'),
  seed('community.toast.pushOn', 'Channel push on — occasional alerts when people message (max ~1/10 min).', '频道推送已开启——有新消息时偶尔提醒（约每 10 分钟最多 1 次）。', 'चैनल पुश चालू — संदेशों पर कभी-कभी अलर्ट (~10 मि में 1)।', 'Push del canal activado — alertas ocasionales (máx. ~1/10 min).', 'Notifications push du canal activées — alertes occasionnelles (max ~1/10 min).', 'إشعارات الدفع للقناة مفعّلة — تنبيهات أحيانًا (حد أقصى ~1/10 د).', 'চ্যানেল পুশ চালু — মাঝে মাঝে সতর্কতা (~১০ মি-তে ১)।', 'Push do canal ativo — alertas ocasionais (máx. ~1/10 min).', 'Push канала включён — редкие уведомления (макс. ~1/10 мин).', 'چینل پش آن — کبھی کبھی الرٹ (~۱۰ من میں ۱)۔'),
  seed('community.toast.pushOff', 'Channel push off for this channel.', '此频道推送已关闭。', 'इस चैनल के लिए पुश बंद।', 'Push del canal desactivado.', 'Notifications push désactivées pour ce canal.', 'تم إيقاف دفع الإشعارات لهذه القناة.', 'এই চ্যানেলে পুশ বন্ধ।', 'Push desativado neste canal.', 'Push для этого канала выключен.', 'اس چینل کے لیے پش بند۔'),
  seed('community.alert.noSendPermission', "You don't have permission to send messages in this channel.", '您没有在此频道发送消息的权限。', 'इस चैनल में संदेश भेजने की अनुमति नहीं है।', 'No tienes permiso para enviar mensajes en este canal.', "Vous n'avez pas la permission d'envoyer des messages sur ce canal.", 'ليس لديك إذن لإرسال رسائل في هذه القناة.', 'এই চ্যানেলে বার্তা পাঠানোর অনুমতি নেই।', 'Sem permissão para enviar mensagens neste canal.', 'Нет прав на отправку сообщений в этом канале.', 'اس چینل میں پیغام بھیجنے کی اجازت نہیں۔'),
  seed('community.alert.gifSendFailed', 'Failed to send GIF. Please try again.', '发送 GIF 失败，请重试。', 'GIF नहीं भेजा जा सका।', 'No se pudo enviar el GIF.', "Échec de l'envoi du GIF.", 'فشل إرسال GIF.', 'GIF পাঠাতে ব্যর্থ।', 'Falha ao enviar GIF.', 'Не удалось отправить GIF.', 'GIF بھیجنے میں ناکامی۔'),
  seed('community.alert.cannotDeleteCategory', 'Cannot delete category "{{name}}" because it contains {{count}} channel(s). Please move or delete all channels first.', '无法删除分类“{{name}}”，其中包含 {{count}} 个频道。请先移动或删除所有频道。', '"{{name}}" हटाया नहीं जा सकता: {{count}} चैनल। पहले चैनल हटाएँ।', 'No se puede eliminar "{{name}}": contiene {{count}} canal(es). Mueva o elimine primero.', 'Impossible de supprimer « {{name}} » : {{count}} canal(aux). Déplacez ou supprimez-les.', 'لا يمكن حذف "{{name}}" لأنها تحتوي على {{count}} قناة.', '"{{name}}" মুছতে পারবেন না: {{count}} চ্যানেল।', 'Não é possível excluir "{{name}}": há {{count}} canal(is).', 'Нельзя удалить «{{name}}»: в ней {{count}} канал(ов).', '"{{name}}" حذف نہیں: {{count}} چینلز۔'),
  seed('community.alert.deleteCategoryFailed', 'Failed to delete category. Please try again.', '删除分类失败，请重试。', 'श्रेणी नहीं हटाई जा सकी।', 'No se pudo eliminar la categoría.', 'Échec de la suppression de la catégorie.', 'فشل حذف الفئة.', 'ক্যাটাগরি মুছতে ব্যর্থ।', 'Falha ao excluir categoria.', 'Не удалось удалить категорию.', 'زمرہ حذف ناکام۔'),
  seed('community.alert.renameCategoryEmpty', 'Category name cannot be empty', '分类名称不能为空', 'श्रेणी का नाम खाली नहीं हो सकता', 'El nombre no puede estar vacío', 'Le nom ne peut pas être vide', 'اسم الفئة لا يمكن أن يكون فارغًا', 'ক্যাটাগরির নাম খালি হতে পারে না', 'O nome não pode estar vazio', 'Имя категории не может быть пустым', 'زمرے کا نام خالی نہیں'),
  seed('community.alert.renameCategoryFailed', 'Failed to rename category. Please try again.', '重命名分类失败，请重试。', 'नाम बदलने में विफल।', 'No se pudo renombrar la categoría.', 'Échec du renommage.', 'فشل إعادة التسمية.', 'নাম পরিবর্তন ব্যর্থ।', 'Falha ao renomear categoria.', 'Не удалось переименовать категорию.', 'نام بدلنا ناکام۔'),
  seed('community.alert.fileCannotDownload', 'File "{{fileName}}" cannot be downloaded. File data is not available.', '无法下载文件“{{fileName}}”。文件数据不可用。', '"{{fileName}}" डाउनलोड नहीं हो सकता। डेटा उपलब्ध नहीं।', 'No se puede descargar "{{fileName}}". Datos no disponibles.', 'Impossible de télécharger « {{fileName}} ». Données indisponibles.', 'لا يمكن تنزيل "{{fileName}}". البيانات غير متوفرة।', '"{{fileName}}" ডাউনলোড করা যাবে না।', 'Não é possível baixar "{{fileName}}".', 'Нельзя скачать «{{fileName}}». Данные недоступны.', '"{{fileName}}" ڈاؤن لوڈ نہیں ہو سکتا۔'),
  seed('community.alert.editMessageFailed', 'Failed to edit message. Please try again.', '编辑消息失败，请重试。', 'संदेश संपादित नहीं हो सका।', 'No se pudo editar el mensaje.', "Échec de la modification du message.", 'فشل تعديل الرسالة.', 'বার্তা সম্পাদনা ব্যর্থ।', 'Falha ao editar mensagem.', 'Не удалось изменить сообщение.', 'پیغام میں ترمیم ناکام۔'),
  seed('community.alert.deleteMessageFailed', 'Failed to delete message: {{detail}}', '删除消息失败：{{detail}}', 'संदेश हटाने में विफल: {{detail}}', 'Error al eliminar: {{detail}}', 'Échec de la suppression : {{detail}}', 'فشل حذف الرسالة: {{detail}}', 'মুছতে ব্যর্থ: {{detail}}', 'Falha ao excluir: {{detail}}', 'Не удалось удалить: {{detail}}', 'حذف ناکام: {{detail}}'),
  seed('community.alert.unknownError', 'Unknown error', '未知错误', 'अज्ञात त्रुटि', 'Error desconocido', 'Erreur inconnue', 'خطأ غير معروف', 'অজানা ত্রুটি', 'Erro desconhecido', 'Неизвестная ошибка', 'نامعلوم خرابی'),
  seed('community.confirm.deleteChannel', 'Delete channel "{{name}}"? This cannot be undone.', '删除频道“{{name}}”？此操作无法撤销。', 'चैनल "{{name}}" हटाएँ? पूर्ववत नहीं।', '¿Eliminar canal "{{name}}"? No se puede deshacer.', 'Supprimer le canal « {{name}} » ? Irréversible.', 'حذف القناة "{{name}}"؟ لا يمكن التراجع.', 'চ্যানেল "{{name}}" মুছবেন? পূর্বাবস্থায় ফেরা যাবে না।', 'Excluir canal "{{name}}"? Não dá para desfazer.', 'Удалить канал «{{name}}»? Это необратимо.', 'چینل "{{name}}" حذف کریں؟ واپس نہیں۔'),
  seed('community.confirm.deleteCategory', 'Delete category "{{name}}"? This cannot be undone.', '删除分类“{{name}}”？此操作无法撤销。', 'श्रेणी "{{name}}" हटाएँ?', '¿Eliminar categoría "{{name}}"?', 'Supprimer la catégorie « {{name}} » ?', 'حذف الفئة "{{name}}"؟', 'ক্যাটাগরি "{{name}}" মুছবেন?', 'Excluir categoria "{{name}}"?', 'Удалить категорию «{{name}}»?', 'زمرہ "{{name}}" حذف کریں؟'),
  seed('community.channelAction.nameRequired', 'Channel name is required.', '需要填写频道名称。', 'चैनल का नाम आवश्यक है।', 'El nombre del canal es obligatorio.', 'Le nom du canal est requis.', 'اسم القناة مطلوب।', 'চ্যানেলের নাম প্রয়োজন।', 'O nome do canal é obrigatório.', 'Нужно указать имя канала.', 'چینل کا نام ضروری ہے۔'),
  seed('community.channelAction.created', 'Channel created successfully.', '频道创建成功。', 'चैनल बनाया गया।', 'Canal creado correctamente.', 'Canal créé avec succès.', 'تم إنشاء القناة بنجاح।', 'চ্যানেল তৈরি হয়েছে।', 'Canal criado com sucesso.', 'Канал успешно создан.', 'چینل بن گیا۔'),
  seed('community.channelAction.deleted', 'Channel deleted successfully.', '频道已删除。', 'चैनल हटाया गया।', 'Canal eliminado.', 'Canal supprimé.', 'تم حذف القناة.', 'চ্যানেল মুছে ফেলা হয়েছে।', 'Canal excluído.', 'Канал удалён.', 'چینل حذف ہو گیا۔'),
  seed('community.channelAction.updated', 'Channel updated successfully.', '频道已更新。', 'चैनल अपडेट हुआ।', 'Canal actualizado.', 'Canal mis à jour.', 'تم تحديث القناة.', 'চ্যানেল আপডেট হয়েছে।', 'Canal atualizado.', 'Канал обновлён.', 'چینل اپ ڈیٹ ہو گیا۔'),
  seed('community.channelAction.createFailed', 'Failed to create channel.', '创建频道失败。', 'चैनल नहीं बनाया जा सका।', 'No se pudo crear el canal.', 'Échec de la création du canal.', 'فشل إنشاء القناة.', 'চ্যানেল তৈরি ব্যর্থ।', 'Falha ao criar canal.', 'Не удалось создать канал.', 'چینل بنانا ناکام۔'),
  seed('community.channelAction.deleteFailed', 'Failed to delete channel.', '删除频道失败。', 'चैनल नहीं हटाया जा सका।', 'No se pudo eliminar el canal.', 'Échec de la suppression du canal.', 'فشل حذف القناة.', 'চ্যানেল মুছতে ব্যর্থ।', 'Falha ao excluir canal.', 'Не удалось удалить канал.', 'چینل حذف ناکام۔'),
  seed('community.channelAction.updateFailed', 'Failed to update channel.', '更新频道失败。', 'चैनल अपडेट नहीं हुआ।', 'No se pudo actualizar el canal.', 'Échec de la mise à jour du canal.', 'فشل تحديث القناة.', 'চ্যানেল আপডেট ব্যর্থ।', 'Falha ao atualizar canal.', 'Не удалось обновить канал.', 'چینل اپ ڈیٹ ناکام۔'),
  seed('community.onlineNow', 'Online Now', '当前在线', 'अभी ऑनलाइन', 'En línea ahora', 'En ligne maintenant', 'متصل الآن', 'এখন অনলাইন', 'Online agora', 'Сейчас в сети', 'ابھی آن لائن'),
  seed('community.manage', 'Manage', '管理', 'प्रबंधित', 'Gestionar', 'Gérer', 'إدارة', 'পরিচালনা', 'Gerenciar', 'Управление', 'منظم کریں'),
  seed('community.pushOn', 'Push on', '推送开', 'पुश चालू', 'Push activado', 'Push activé', 'دفع مفعّل', 'পুশ চালু', 'Push ligado', 'Push вкл.', 'پش آن'),
  seed('community.pushOff', 'Push off', '推送关', 'पुश बंद', 'Push desactivado', 'Push désactivé', 'دفع متوقف', 'পুশ বন্ধ', 'Push desligado', 'Push выкл.', 'پش آف'),
  seed('community.pushTitleOn', 'Stop push alerts for new messages in this channel', '停止此频道新消息的推送提醒', 'इस चैनल में नए संदेशों के लिए पुश बंद करें', 'Detener alertas push de mensajes nuevos en este canal', 'Désactiver les alertes push pour ce canal', 'إيقاف تنبيهات الدفع للرسائل الجديدة في هذه القناة', 'এই চ্যানেলে নতুন বার্তার পুশ বন্ধ করুন', 'Parar alertas push de novas mensagens neste canal', 'Отключить push-уведомления о новых сообщениях в канале', 'اس چینل میں نئے پیغامات کی پش الرٹ بند کریں'),
  seed('community.pushTitleOff', 'Get push when people chat here (throttled, ~1 per 10 min per channel)', '在此聊天时接收推送（节流，每频道约每 10 分钟 1 次）', 'यहाँ चैट पर पुश (थ्रॉटल, ~10 मि में 1)', 'Recibe push al chatear aquí (~1 cada 10 min por canal)', 'Recevoir des push ici (~1 / 10 min par canal)', 'تنبيهات عند الدردشة (~1 كل 10 د لكل قناة)', 'চ্যাটে পুশ (~১০ মি-তে ১)', 'Receber push ao conversar (~1 a cada 10 min)', 'Push при сообщениях (~1 раз в 10 мин на канал)', 'چیٹ پر پش (~۱۰ من میں ۱)'),
  seed('community.alerts.deniedBody', 'System alerts are off or blocked. Unmute AURA TERMINAL™ in your device settings to get message-style notifications when the app is in the background.', '系统通知已关闭或被阻止。请在设备设置中取消静音 AURA TERMINAL™，以便在后台接收消息式通知。', 'सिस्टम अलर्ट बंद या ब्लॉक हैं। बैकग्राउंड में सूचनाओं के लिए डिवाइस सेटिंग्स में AURA TERMINAL™ अनम्यूट करें।', 'Las alertas del sistema están desactivadas o bloqueadas. Reactiva AURA TERMINAL™ en ajustes para notificaciones en segundo plano.', 'Les alertes système sont coupées ou bloquées. Réactivez AURA TERMINAL™ dans les réglages pour des notifications en arrière-plan.', 'تنبيهات النظام متوقفة أو محظورة. ألغِ كتم AURA TERMINAL™ في إعدادات الجهاز للإشعارات في الخلفية.', 'সিস্টেম অ্যালার্ট বন্ধ বা ব্লক। ব্যাকগ্রাউন্ডে নোটিফিকেশনের জন্য সেটিংসে AURA TERMINAL™ আনমিউট করুন।', 'Alertas do sistema desativadas ou bloqueadas. Reative AURA TERMINAL™ nas configurações para notificações em segundo plano.', 'Системные уведомления выключены или заблокированы. Включите AURA TERMINAL™ в настройках устройства.', 'سسٹم الرٹ بند یا بلاک۔ بیک گراؤنڈ نوٹیفیکیشن کے لیے AURA TERMINAL™ آن میوٹ کریں۔'),
  seed('community.alerts.promptBody', 'Enable alerts to get notified of new messages and mentions (muted channels stay silent).', '开启通知以接收新消息和提及（已静音频道仍保持静音）。', 'नए संदेशों और मेंशन के लिए अलर्ट चालू करें (म्यूट चैनल शांत रहेंगे)।', 'Activa alertas para mensajes y menciones (los canales silenciados siguen en silencio).', 'Activez les alertes pour les messages et mentions (les canaux muets restent silencieux).', 'فعّل التنبيهات للرسائل والإشارات (القنوات المكتومة تبقى صامتة).', 'নতুন বার্তা ও উল্লেখের জন্য অ্যালার্ট চালু করুন (মিউট চ্যানেল নীরব থাকবে)।', 'Ative alertas para mensagens e menções (canais silenciados permanecem silenciosos).', 'Включите уведомления о сообщениях и упоминаниях (заглушённые каналы без звука).', 'نئے پیغامات اور تذکروں کے لیے الرٹ آن کریں (خاموش چینل خاموش رہیں گے)۔'),
  seed('community.alerts.enable', 'Enable alerts', '开启通知', 'अलर्ट चालू करें', 'Activar alertas', 'Activer les alertes', 'تفعيل التنبيهات', 'অ্যালার্ট চালু', 'Ativar alertas', 'Включить уведомления', 'الرٹ آن'),
  seed('community.alerts.dismiss', 'Dismiss', '关闭', 'खारिज', 'Descartar', 'Fermer', 'تجاهل', 'বাতিল', 'Dispensar', 'Скрыть', 'برخاست'),
  seed('community.aria.toggleChannels', 'Toggle channels', '切换频道列表', 'चैनल टॉगल', 'Mostrar/ocultar canales', 'Afficher/masquer les canaux', 'تبديل القنوات', 'চ্যানেল টগল', 'Alternar canais', 'Показать/скрыть каналы', 'چینلز ٹوگل'),
  seed('community.wsReconnectBody', 'Real-time connection unavailable. Messages will update via polling.', '实时连接不可用。消息将通过轮询更新。', 'रीयल-टाइम कनेक्शन उपलब्ध नहीं। संदेश पोलिंग से अपडेट होंगे।', 'Conexión en tiempo real no disponible. Los mensajes se actualizarán por sondeo.', 'Connexion temps réel indisponible. Mise à jour par interrogation.', 'الاتصال اللحظي غير متاح. ستُحدَّث الرسائل عبر الاستعلام.', 'রিয়েল-টাইম সংযোগ নেই। বার্তা পোলিং দিয়ে আপডেট হবে।', 'Conexão em tempo real indisponível. Atualização por consulta.', 'Нет соединения в реальном времени. Обновление через опрос.', 'ریئل ٹائم کنکشن دستیاب نہیں۔ پیغام پولنگ سے اپ ڈیٹ ہوں گے۔'),
  seed('community.wsRetryConnection', 'Retry connection', '重试连接', 'कनेक्शन पुनः प्रयास', 'Reintentar conexión', 'Réessayer la connexion', 'إعادة محاولة الاتصال', 'সংযোগ পুনরায় চেষ্টা', 'Tentar conexão novamente', 'Повторить подключение', 'کنکشن دوبارہ'),
  seed('community.conn.connected', 'Connected', '已连接', 'जुड़ा हुआ', 'Conectado', 'Connecté', 'متصل', 'সংযুক্ত', 'Conectado', 'Подключено', 'منسلک'),
  seed('community.conn.serverIssue', 'Connection Issues', '连接问题', 'कनेक्शन समस्या', 'Problemas de conexión', 'Problèmes de connexion', 'مشاكل الاتصال', 'সংযোগ সমস্যা', 'Problemas de conexão', 'Проблемы соединения', 'کنکشن مسئلہ'),
  seed('community.conn.wifiIssue', 'Cannot Connect', '无法连接', 'कनेक्ट नहीं हो सका', 'No se puede conectar', 'Impossible de se connecter', 'تعذر الاتصال', 'সংযোগ করা যাচ্ছে না', 'Não é possível conectar', 'Нет подключения', 'کنکٹ نہیں'),
  seed('community.conn.connecting', 'Connecting...', '连接中...', 'कनेक्ट हो रहा...', 'Conectando...', 'Connexion...', 'جارٍ الاتصال...', 'সংযোগ হচ্ছে...', 'Conectando...', 'Подключение...', 'منسلک ہو رہا...'),
  seed('community.readOnly.adminChannel', 'This channel is read-only. Only admins can post here.', '此频道为只读。仅管理员可发帖。', 'यह चैनल केवल पढ़ने योग्य है। केवल एडमिन पोस्ट कर सकते हैं।', 'Este canal es solo lectura. Solo los administradores pueden publicar.', 'Ce canal est en lecture seule. Seuls les admins peuvent publier.', 'هذه القناة للقراءة فقط. يمكن للمسؤولين فقط النشر.', 'এই চ্যানেল শুধু পঠন। শুধু অ্যাডমিন পোস্ট করতে পারেন।', 'Este canal é somente leitura. Só administradores podem postar.', 'Канал только для чтения. Публиковать могут только админы.', 'یہ چینل صرف پڑھنے کے لیے۔ صرف ایڈمن پوسٹ کر سکتے ہیں۔'),
  seed('community.readOnly.upgradeChannel', 'This channel is read-only. Upgrade to post here.', '此频道为只读。升级后可发帖。', 'यह चैनल केवल पढ़ने योग्य है। पोस्ट करने के लिए अपग्रेड करें।', 'Este canal es solo lectura. Mejora tu plan para publicar.', 'Ce canal est en lecture seule. Passez à un niveau supérieur pour publier.', 'هذه القناة للقراءة فقط. ترقية للنشر.', 'এই চ্যানেল শুধু পঠন। পোস্ট করতে আপগ্রেড করুন।', 'Este canal é somente leitura. Faça upgrade para postar.', 'Канал только для чтения. Оформите подписку, чтобы писать.', 'یہ چینل صرف پڑھنے کے لیے۔ پوسٹ کے لیے اپ گریڈ کریں۔'),
  seed('community.editing.label', 'Editing message', '正在编辑消息', 'संदेश संपादन', 'Editando mensaje', 'Modification du message', 'تعديل الرسالة', 'বার্তা সম্পাদনা', 'Editando mensagem', 'Редактирование сообщения', 'پیغام میں ترمیم'),
  seed('community.editing.hint', 'Make your changes and click Save', '修改后点击保存', 'बदलाव करें और सहेजें पर क्लिक करें', 'Haz cambios y pulsa Guardar', 'Modifiez puis cliquez sur Enregistrer', 'عدّل ثم انقر حفظ', 'পরিবর্তন করে সংরক্ষণ ক্লিক করুন', 'Faça alterações e clique em Salvar', 'Внесите изменения и нажмите Сохранить', 'تبدیلی کریں اور محفوظ پر کلک'),
  seed('community.cancel', 'Cancel', '取消', 'रद्द', 'Cancelar', 'Annuler', 'إلغاء', 'বাতিল', 'Cancelar', 'Отмена', 'منسوخ'),
  seed('community.save', 'Save', '保存', 'सहेजें', 'Guardar', 'Enregistrer', 'حفظ', 'সংরক্ষণ', 'Salvar', 'Сохранить', 'محفوظ'),
  seed('community.saving', 'Saving...', '保存中...', 'सहेज रहा...', 'Guardando...', 'Enregistrement...', 'جارٍ الحفظ...', 'সংরক্ষণ...', 'Salvando...', 'Сохранение...', 'محفوظ ہو رہا...'),
  seed('community.placeholder.editMessage', 'Edit your message...', '编辑您的消息...', 'अपना संदेश संपादित करें...', 'Edita tu mensaje...', 'Modifiez votre message...', 'عدّل رسالتك...', 'আপনার বার্তা সম্পাদনা...', 'Edite sua mensagem...', 'Редактируйте сообщение...', 'اپنا پیغام ترمیم...'),
  seed('community.placeholder.messageChannel', 'Message #{{channel}}', '在 #{{channel}} 发消息', '#{{channel}} में संदेश', 'Mensaje en #{{channel}}', 'Message dans #{{channel}}', 'رسالة في #{{channel}}', '#{{channel}}-এ বার্তা', 'Mensagem em #{{channel}}', 'Сообщение в #{{channel}}', '#{{channel}} میں پیغام'),
  seed('community.placeholder.readOnlyAdmin', 'Read-only. Only admins can post here.', '只读。仅管理员可发帖。', 'केवल पढ़ें। केवल एडमिन।', 'Solo lectura. Solo admins.', 'Lecture seule. Admins seulement.', 'للقراءة فقط. المسؤولون فقط.', 'শুধু পঠন। শুধু অ্যাডমিন।', 'Somente leitura. Só admins.', 'Только чтение. Только админы.', 'صرف پڑھیں۔ صرف ایڈمن۔'),
  seed('community.placeholder.readOnlyUpgrade', 'Read-only channel. Upgrade to post here.', '只读频道。升级后可发帖。', 'केवल पढ़ें। पोस्ट के लिए अपग्रेड।', 'Solo lectura. Mejora para publicar.', 'Lecture seule. Passez au niveau supérieur.', 'للقراءة فقط. ترقية للنشر.', 'শুধু পঠন। পোস্টের জন্য আপগ্রেড।', 'Somente leitura. Faça upgrade.', 'Только чтение. Оформите подписку.', 'صرف پڑھیں۔ پوسٹ کے لیے اپ گریڈ۔'),
  seed('community.mention.members', 'Members', '成员', 'सदस्य', 'Miembros', 'Membres', 'الأعضاء', 'সদস্য', 'Membros', 'Участники', 'اراکین'),
  seed('community.mention.notifyAdmins', 'Notify all admins', '通知所有管理员', 'सभी एडमिन को सूचित करें', 'Notificar a todos los admins', 'Notifier tous les admins', 'إخطار جميع المسؤولين', 'সব অ্যাডমিনকে জানান', 'Notificar todos os admins', 'Уведомить всех админов', 'تمام ایڈمنز کو مطلع کریں'),
  seed('community.mention.userFallback', 'User', '用户', 'उपयोगकर्ता', 'Usuario', 'Utilisateur', 'مستخدم', 'ব্যবহারকারী', 'Usuário', 'Пользователь', 'صارف'),
  seed('community.tooltip.send', 'Send message', '发送消息', 'संदेश भेजें', 'Enviar mensaje', 'Envoyer le message', 'إرسال الرسالة', 'বার্তা পাঠান', 'Enviar mensagem', 'Отправить сообщение', 'پیغام بھیجیں'),
  seed('community.tooltip.deleteMessage', 'Delete message', '删除消息', 'संदेश हटाएँ', 'Eliminar mensaje', 'Supprimer le message', 'حذف الرسالة', 'বার্তা মুছুন', 'Excluir mensagem', 'Удалить сообщение', 'پیغام حذف'),
  seed('community.tooltip.channelLocked', 'Requires {{tier}} subscription - Click to subscribe', '需要 {{tier}} 订阅 — 点击订阅', '{{tier}} सदस्यता आवश्यक — सब्सक्राइब करें', 'Requiere suscripción {{tier}} — Clic para suscribirse', 'Abonnement {{tier}} requis — Cliquez pour souscrire', 'يتطلب اشتراك {{tier}} — انقر للاشتراك', '{{tier}} সাবস্ক্রিপশন লাগবে — সাবস্ক্রাইব', 'Assinatura {{tier}} necessária — Clique', 'Нужна подписка {{tier}} — нажмите', '{{tier}} سبسکرپشن — سبسکرائب'),
  seed('community.tooltip.dragReorder', 'Drag to reorder', '拖动排序', 'क्रम बदलने के लिए खींचें', 'Arrastrar para reordenar', 'Glisser pour réorganiser', 'اسحب لإعادة الترتيب', 'পুনরায় সাজাতে টানুন', 'Arrastar para reordenar', 'Перетащите для сортировки', 'ترتیب کے لیے کھینچیں'),
  seed('community.welcome.title', 'Welcome to Aura Terminal™ community', '欢迎来到 Aura Terminal™ 社区', 'Aura Terminal™ समुदाय में आपका स्वागत है', 'Bienvenido a la comunidad de Aura Terminal™', 'Bienvenue dans la communauté Aura Terminal™', 'مرحبًا بك في مجتمع Aura Terminal™', 'Aura Terminal™ কমিউনিটিতে স্বাগতম', 'Bem-vindo à comunidade Aura Terminal™', 'Добро пожаловать в сообщество Aura Terminal™', 'Aura Terminal™ کمیونٹی میں خوش آمدید'),
  seed('community.welcome.subtitle', 'Select a channel to start chatting', '选择频道开始聊天', 'चैट शुरू करने के लिए चैनल चुनें', 'Selecciona un canal para chatear', 'Sélectionnez un canal pour discuter', 'اختر قناة لبدء الدردشة', 'চ্যাট শুরুতে চ্যানেল বেছে নিন', 'Selecione um canal para conversar', 'Выберите канал, чтобы начать чат', 'چیٹ شروع کرنے کے لیے چینل منتخب کریں'),
  seed('community.channelMgr.title', 'CHANNEL MANAGEMENT', '频道管理', 'चैनल प्रबंधन', 'GESTIÓN DE CANALES', 'GESTION DES CANAUX', 'إدارة القنوات', 'চ্যানেল ব্যবস্থাপনা', 'GERENCIAMENTO DE CANAIS', 'УПРАВЛЕНИЕ КАНАЛАМИ', 'چینل مینجمنٹ'),
  seed('community.channelMgr.channelName', 'CHANNEL NAME', '频道名称', 'चैनल नाम', 'NOMBRE DEL CANAL', 'NOM DU CANAL', 'اسم القناة', 'চ্যানেলের নাম', 'NOME DO CANAL', 'ИМЯ КАНАЛА', 'چینل کا نام'),
  seed('community.channelMgr.channelNamePh', 'e.g., Smart Money Concepts', '例如：Smart Money Concepts', 'जैसे Smart Money Concepts', 'ej., Smart Money Concepts', 'ex. Smart Money Concepts', 'مثال: Smart Money Concepts', 'যেমন Smart Money Concepts', 'ex.: Smart Money Concepts', 'напр. Smart Money Concepts', 'مثلاً Smart Money Concepts'),
  seed('community.channelMgr.category', 'CATEGORY', '分类', 'श्रेणी', 'CATEGORÍA', 'CATÉGORIE', 'الفئة', 'ক্যাটাগরি', 'CATEGORIA', 'КАТЕГОРИЯ', 'زمرہ'),
  seed('community.channelMgr.access', 'ACCESS', '访问权限', 'पहुँच', 'ACCESO', 'ACCÈS', 'الوصول', 'অ্যাক্সেস', 'ACESSO', 'ДОСТУП', 'رسائی'),
  seed('community.channelMgr.description', 'DESCRIPTION', '描述', 'विवरण', 'DESCRIPCIÓN', 'DESCRIPTION', 'الوصف', 'বিবরণ', 'DESCRIÇÃO', 'ОПИСАНИЕ', 'تفصیل'),
  seed('community.channelMgr.descPh', 'Describe the purpose of this channel...', '描述此频道的用途...', 'इस चैनल का उद्देश्य बताएँ...', 'Describe el propósito del canal...', 'Décrivez le but du canal...', 'صف غرض هذه القناة...', 'চ্যানেলের উদ্দেশ্য লিখুন...', 'Descreva o propósito do canal...', 'Опишите назначение канала...', 'چینل کا مقصد بیان کریں...'),
  seed('community.channelMgr.createBtn', 'Create Channel', '创建频道', 'चैनल बनाएँ', 'Crear canal', 'Créer un canal', 'إنشاء قناة', 'চ্যানেল তৈরি', 'Criar canal', 'Создать канал', 'چینل بنائیں'),
  seed('community.channelMgr.creating', 'Creating...', '创建中...', 'बन रहा...', 'Creando...', 'Création...', 'جارٍ الإنشاء...', 'তৈরি হচ্ছে...', 'Criando...', 'Создание...', 'بن رہا...'),
  seed('community.channelMgr.existing', 'Existing Channels', '已有频道', 'मौजूदा चैनल', 'Canales existentes', 'Canaux existants', 'القنوات الحالية', 'বিদ্যমান চ্যানেল', 'Canais existentes', 'Существующие каналы', 'موجودہ چینلز'),
  seed('community.channelMgr.channelsCount', '{{count}} channels', '{{count}} 个频道', '{{count}} चैनल', '{{count}} canales', '{{count}} canaux', '{{count}} قناة', '{{count}} চ্যানেল', '{{count}} canais', '{{count}} каналов', '{{count}} چینلز'),
  seed('community.channelMgr.emptyTitle', 'No custom channels yet', '尚无自定义频道', 'अभी कोई कस्टम चैनल नहीं', 'Aún no hay canales personalizados', 'Pas encore de canaux personnalisés', 'لا توجد قنوات مخصصة بعد', 'এখনও কাস্টম চ্যানেল নেই', 'Ainda não há canais personalizados', 'Пользовательских каналов пока нет', 'ابھی کوئی کسٹم چینل نہیں'),
  seed('community.channelMgr.emptySub', 'Create your first channel above', '在上方创建您的第一个频道', 'ऊपर अपना पहला चैनल बनाएँ', 'Crea tu primer canal arriba', 'Créez votre premier canal ci-dessus', 'أنشئ أول قناة أعلاه', 'উপরে প্রথম চ্যানেল তৈরি করুন', 'Crie seu primeiro canal acima', 'Создайте первый канал выше', 'اوپر اپنا پہلا چینل بنائیں'),
  seed('community.channelMgr.delete', 'Delete', '删除', 'हटाएँ', 'Eliminar', 'Supprimer', 'حذف', 'মুছুন', 'Excluir', 'Удалить', 'حذف'),
  seed('community.channelMgr.optForums', '📈 Forums', '📈 论坛', '📈 फ़ोरम', '📈 Foros', '📈 Forums', '📈 المنتديات', '📈 ফোরাম', '📈 Fóruns', '📈 Форумы', '📈 فورمز'),
  seed('community.channelMgr.optGeneral', '💬 General', '💬 综合', '💬 सामान्य', '💬 General', '💬 Général', '💬 عام', '💬 সাধারণ', '💬 Geral', '💬 Общее', '💬 عمومی'),
  seed('community.channelMgr.optSupport', '🆘 Support', '🆘 支持', '🆘 सहायता', '🆘 Soporte', '🆘 Assistance', '🆘 الدعم', '🆘 সাপোর্ট', '🆘 Suporte', '🆘 Поддержка', '🆘 سپورٹ'),
  seed('community.channelMgr.optPremium', '⭐ Premium', '⭐ 高级', '⭐ प्रीमियम', '⭐ Premium', '⭐ Premium', '⭐ بريميوم', '⭐ প্রিমিয়াম', '⭐ Premium', '⭐ Премиум', '⭐ پریمیم'),
  seed('community.channelMgr.optA7fx', '💎 A7FX', '💎 A7FX', '💎 A7FX', '💎 A7FX', '💎 A7FX', '💎 A7FX', '💎 A7FX', '💎 A7FX', '💎 A7FX', '💎 A7FX'),
  seed('community.channelMgr.optStaff', '👨‍💼 Staff', '👨‍💼 工作人员', '👨‍💼 स्टाफ', '👨‍💼 Personal', '👨‍💼 Équipe', '👨‍💼 الطاقم', '👨‍💼 স্টাফ', '👨‍💼 Equipe', '👨‍💼 Персонал', '👨‍💼 اسٹاف'),
  seed('community.channelMgr.accessFree', '🌱 Free', '🌱 免费', '🌱 मुफ़्त', '🌱 Gratis', '🌱 Gratuit', '🌱 مجاني', '🌱 ফ্রি', '🌱 Grátis', '🌱 Бесплатно', '🌱 مفت'),
  seed('community.channelMgr.accessOpen', '🔓 Open', '🔓 开放', '🔓 खुला', '🔓 Abierto', '🔓 Ouvert', '🔓 مفتوح', '🔓 খোলা', '🔓 Aberto', '🔓 Открытый', '🔓 کھلا'),
  seed('community.channelMgr.accessReadOnly', '📖 Read Only', '📖 只读', '📖 केवल पढ़ें', '📖 Solo lectura', '📖 Lecture seule', '📖 للقراءة فقط', '📖 শুধু পঠন', '📖 Somente leitura', '📖 Только чтение', '📖 صرف پڑھیں'),
  seed('community.channelMgr.accessAdminOnly', '🛡 Admin Only', '🛡 仅管理员', '🛡 केवल एडमिन', '🛡 Solo admins', '🛡 Admins seulement', '🛡 للمسؤولين فقط', '🛡 শুধু অ্যাডমিন', '🛡 Só admins', '🛡 Только админы', '🛡 صرف ایڈمن'),
  seed('community.channelMgr.accessPremium', '✨ Premium (£99/mo)', '✨ 高级（£99/月）', '✨ प्रीमियम (£99/माह)', '✨ Premium (£99/mes)', '✨ Premium (99 £/mois)', '✨ بريميوم (£99/شهر)', '✨ প্রিমিয়াম (£99/মাস)', '✨ Premium (£99/mês)', '✨ Премиум (£99/мес)', '✨ پریمیم (£99/ماہ)'),
  seed('community.channelMgr.accessA7fx', '💎 A7FX Elite (£250/mo)', '💎 A7FX 精英（£250/月）', '💎 A7FX एलीट (£250/माह)', '💎 A7FX Elite (£250/mes)', '💎 A7FX Elite (250 £/mois)', '💎 A7FX Elite (£250/شهر)', '💎 A7FX এলিট (£250/মাস)', '💎 A7FX Elite (£250/mês)', '💎 A7FX Elite (£250/мес)', '💎 A7FX ایلیٹ (£250/ماہ)'),
  seed('community.badge.premium', 'Premium', '高级', 'प्रीमियम', 'Premium', 'Premium', 'بريميوم', 'প্রিমিয়াম', 'Premium', 'Премиум', 'پریمیم'),
  seed('community.badge.elite', 'Elite', '精英', 'एलीट', 'Élite', 'Élite', 'نخبة', 'এলিট', 'Elite', 'Элита', 'ایلیٹ'),
  seed('community.badge.admin', 'Admin', '管理员', 'एडमिन', 'Admin', 'Admin', 'مسؤول', 'অ্যাডমিন', 'Admin', 'Админ', 'ایڈمن'),
  seed('community.badge.readOnly', 'Read Only', '只读', 'केवल पढ़ें', 'Solo lectura', 'Lecture seule', 'للقراءة فقط', 'শুধু পঠন', 'Somente leitura', 'Только чтение', 'صرف پڑھیں'),
  seed('community.badge.free', 'Free', '免费', 'मुफ़्त', 'Gratis', 'Gratuit', 'مجاني', 'ফ্রি', 'Grátis', 'Бесплатно', 'مفت'),
  seed('community.badge.open', 'Open', '开放', 'खुला', 'Abierto', 'Ouvert', 'مفتوح', 'খোলা', 'Aberto', 'Открытый', 'کھلا'),
  seed('community.deleteModal.title', 'Delete Message', '删除消息', 'संदेश हटाएँ', 'Eliminar mensaje', 'Supprimer le message', 'حذف الرسالة', 'বার্তা মুছুন', 'Excluir mensagem', 'Удалить сообщение', 'پیغام حذف'),
  seed('community.deleteModal.body', 'Are you sure you want to delete this message? This action cannot be undone.', '确定要删除此消息吗？此操作无法撤销。', 'क्या आप यह संदेश हटाना चाहते हैं? पूर्ववत नहीं किया जा सकता।', '¿Seguro que quieres eliminar este mensaje? No se puede deshacer.', 'Voulez-vous vraiment supprimer ce message ? Irréversible.', 'هل تريد حذف هذه الرسالة؟ لا يمكن التراجع.', 'আপনি কি এই বার্তা মুছতে চান? পূর্বাবস্থায় ফেরা যাবে না।', 'Tem certeza de que deseja excluir esta mensagem? Não dá para desfazer.', 'Удалить это сообщение? Действие необратимо.', 'کیا آپ یہ پیغام حذف کرنا چاہتے ہیں؟ واپس نہیں۔'),
  seed('community.deleteModal.deleting', 'Deleting...', '删除中...', 'हट रहा...', 'Eliminando...', 'Suppression...', 'جارٍ الحذف...', 'মুছে ফেলা হচ্ছে...', 'Excluindo...', 'Удаление...', 'حذف ہو رہا...'),
  seed('community.deleteModal.confirm', 'Delete Message', '删除消息', 'संदेश हटाएँ', 'Eliminar mensaje', 'Supprimer le message', 'حذف الرسالة', 'বার্তা মুছুন', 'Excluir mensagem', 'Удалить сообщение', 'پیغام حذف'),
  seed('community.context.copyMessageLink', 'Copy message link', '复制消息链接', 'संदेश लिंक कॉपी', 'Copiar enlace del mensaje', 'Copier le lien du message', 'نسخ رابط الرسالة', 'বার্তার লিঙ্ক কপি', 'Copiar link da mensagem', 'Копировать ссылку на сообщение', 'پیغام کا لنک کاپی'),
  seed('community.context.saveMessage', 'Save Message', '保存消息', 'संदेश सहेजें', 'Guardar mensaje', 'Enregistrer le message', 'حفظ الرسالة', 'বার্তা সংরক্ষণ', 'Salvar mensagem', 'Сохранить сообщение', 'پیغام محفوظ'),
  seed('community.context.notifyReplies', 'Notify on Replies', '回复时通知', 'जवाबों पर सूचित', 'Notificar en respuestas', 'Notifier les réponses', 'إخطار عند الردود', 'উত্তরে জানান', 'Notificar respostas', 'Уведомлять об ответах', 'جوابات پر مطلع'),
  seed('community.context.markUnread', 'Mark as Unread', '标记为未读', 'अपठित चिह्नित', 'Marcar como no leído', 'Marquer comme non lu', 'وضع كغير مقروء', 'অপঠিত চিহ্নিত', 'Marcar como não lida', 'Пометить непрочитанным', 'غیر پڑھا'),
  seed('community.context.reportMessage', 'Report message', '举报消息', 'संदेश रिपोर्ट', 'Denunciar mensaje', 'Signaler le message', 'الإبلاغ عن الرسالة', 'বার্তা রিপোর্ট', 'Denunciar mensagem', 'Пожаловаться на сообщение', 'پیغام رپورٹ'),
  seed('community.context.deleteMessage', 'Delete message', '删除消息', 'संदेश हटाएँ', 'Eliminar mensaje', 'Supprimer le message', 'حذف الرسالة', 'বার্তা মুছুন', 'Excluir mensagem', 'Удалить сообщение', 'پیغام حذف'),
  seed('community.toast.xpAwarded', '+{{xp}} XP!', '+{{xp}} 经验！', '+{{xp}} XP!', '¡+{{xp}} XP!', '+{{xp}} XP !', '+{{xp}} XP!', '+{{xp}} XP!', '+{{xp}} XP!', '+{{xp}} XP!', '+{{xp}} XP!'),
];

function esc(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function rowToStr(row) {
  const parts = LANGS.map((lng) => `${lng === 'zh-CN' ? "'zh-CN'" : lng}: '${esc(row[lng])}'`);
  return `  { k: '${esc(row.k)}', ${parts.join(', ')} },`;
}

const header = `/** @typedef {{ k: string, en: string, 'zh-CN': string, hi: string, es: string, fr: string, ar: string, bn: string, pt: string, ru: string, ur: string }} Row */
/** @type {Row[]} */
/* eslint-disable max-len */
export const rows = [
`;

const footer = `
];
`;

const out = path.join(__dirname, 'i18n-part6.mjs');
fs.writeFileSync(out, header + rows.map(rowToStr).join('\n') + footer, 'utf8');
console.log('Wrote', out, 'rows:', rows.length);
