import { REPLAY_PATTERN_OPTIONS } from '../../utils/traderSuite';

export const REPLAY_MODES = {
  scenario: 'scenario',
  day: 'day',
  trade: 'trade',
};

export const REPLAY_STATUSES = {
  draft: 'draft',
  inProgress: 'in_progress',
  completed: 'completed',
};

export const SCENARIO_TYPES = [
  { id: 'worst_trades', label: 'Worst trades', hint: 'Largest drawdowns and costly mistakes' },
  { id: 'best_trades', label: 'Best trades', hint: 'Highest-quality executions to reinforce' },
  { id: 'losing_trades', label: 'Losing trades', hint: 'Losses to process without shame' },
  { id: 'breakeven_trades', label: 'Break-even trades', hint: 'Scratch trades and fee-heavy flat days' },
  { id: 'poor_entry_timing', label: 'Poor entry timing', hint: 'Late chase or early impulse' },
  { id: 'poor_discipline', label: 'Poor discipline', hint: 'Rules broken, size or boredom trades' },
  { id: 'poor_exits', label: 'Poor exits', hint: 'Runners cut, stops too tight, premature exit' },
  { id: 'high_missed_r', label: 'High missed R', hint: 'Left meaningful money on the table' },
  { id: 'custom', label: 'Custom selection', hint: 'Pick from your library with filters' },
];

export const PLAYBACK_MS_MIN = 400;
export const PLAYBACK_MS_MAX = 60000;

export function clampPlaybackSpeedMs(ms) {
  const n = Number(ms);
  if (!Number.isFinite(n)) return 2500;
  return Math.min(PLAYBACK_MS_MAX, Math.max(PLAYBACK_MS_MIN, Math.round(n)));
}

export const PLAYBACK_SPEED_OPTIONS = [
  { label: '0.5x', ms: 4000 },
  { label: '1x', ms: 2500 },
  { label: '1.5x', ms: 1700 },
  { label: '2x', ms: 1250 },
  { label: '3x', ms: 800 },
];

export const CHART_INTERVAL_OPTIONS = [
  { label: '1m', value: '1' },
  { label: '5m', value: '5' },
  { label: '15m', value: '15' },
  { label: '30m', value: '30' },
  { label: '45m', value: '45' },
  { label: '1H', value: '60' },
  { label: '4H', value: '240' },
  { label: '1d', value: '1D' },
  { label: '1w', value: '1W' },
  { label: '1mo', value: '1M' },
  { label: '1y', value: '1Y' },
];

export const MARKER_TYPES = [
  'entry',
  'confirmation',
  'risk',
  'management',
  'exit',
  'invalidation',
  'lesson',
  'mistake',
];

/** Demo template for guided tour — not persisted until user saves */
export const DEMO_REPLAY_TEMPLATE = {
  title: 'EURUSD · London reclaim (guided example)',
  symbol: 'OANDA:EURUSD',
  interval: '15',
  asset: 'EURUSD',
  direction: 'Long',
  outcome: 'Win',
  rResult: '2.5R',
  entry: '1.2748',
  stop: '1.2729',
  target: '1.2796',
  exit: '1.2791',
  marketState: 'Trend continuation',
  biasAtTime: 'Bullish',
  confidenceLevel: '74%',
  keyDrivers: 'London low sweep, reclaim, and aligned Aura bias.',
  entryTiming: 7,
  discipline: 6,
  patience: 5,
  verdict: 'Good trade, but the runner was managed too tightly.',
  mfe: '3.1R',
  mae: '0.4R',
  missedR: '0.7R',
  actualR: '2.5R',
  insight: 'Wait for the reclaim close and give the runner more room once 1R is secured.',
  patternInsight: REPLAY_PATTERN_OPTIONS[0],
  linkedPlaybook: 'London Breakout',
  linkedLabDate: '2026-04-01',
  replayStep: 0,
  mode: REPLAY_MODES.trade,
  scenarioType: '',
  replayStatus: REPLAY_STATUSES.draft,
  playbackSpeedMs: 2500,
  replayDate: null,
  sourceDate: '2026-04-01',
  notes: '',
  emotionalState: '',
  whatISaw: '',
  whatIMissed: '',
  improvementPlan: '',
  lessonSummary: '',
  ruleFollowed: '',
  reviewBiggestMistake: '',
  reviewBestMoment: '',
  tradeRef: '',
  completedAt: null,
  pnl: '',
  autoFocusNotes: true,
  showLessons: true,
  replayMarkers: [
    {
      id: 'demo_mk_0',
      label: 'Valid entry zone',
      timestampLabel: '08:35',
      type: 'entry',
      title: 'Structure reclaimed after liquidity sweep',
      body: 'Zone forms when prior structure is reclaimed and the sweep is repaired — not on the first wick.',
      lesson: 'Wait for reclaim plus intentional close, not only a sharp wick.',
      confidence: 82,
      orderIndex: 0,
      scoreImpact: 4,
      tags: ['london', 'liquidity'],
    },
    {
      id: 'demo_mk_1',
      label: 'Confirmation',
      timestampLabel: '08:47',
      type: 'confirmation',
      title: 'Momentum confirms the bias',
      body: 'A clean M5 close through the reclaim level confirms participation, not just a stop hunt.',
      lesson: 'Confirmation should align timeframe hierarchy with your playbook.',
      confidence: 78,
      orderIndex: 1,
      scoreImpact: 3,
      tags: ['m5', 'momentum'],
    },
    {
      id: 'demo_mk_2',
      label: 'Late entry risk',
      timestampLabel: '08:56',
      type: 'mistake',
      title: 'Chasing compresses R',
      body: 'Entering after the impulse leg shortens distance to stop and caps runner potential.',
      lesson: 'If you missed the pivot, wait for the next valid shelf rather than forcing.',
      confidence: 71,
      orderIndex: 2,
      scoreImpact: -4,
      tags: ['timing'],
    },
    {
      id: 'demo_mk_3',
      label: 'Invalidation',
      timestampLabel: '09:12',
      type: 'invalidation',
      title: 'Where thesis dies',
      body: 'Loss of the reclaim low would invalidate the continuation read — exits belong before denial.',
      lesson: 'Define invalidation before you add size; honour it without negotiation.',
      confidence: 88,
      orderIndex: 3,
      scoreImpact: 5,
      tags: ['risk', 'invalidation'],
    },
  ],
};

export function emptySessionDraft(overrides = {}) {
  return {
    title: 'New replay',
    symbol: 'OANDA:EURUSD',
    interval: '15',
    asset: 'EURUSD',
    direction: 'Long',
    outcome: '',
    rResult: '',
    entry: '',
    stop: '',
    target: '',
    exit: '',
    marketState: '',
    biasAtTime: '',
    confidenceLevel: '',
    keyDrivers: '',
    entryTiming: 5,
    discipline: 5,
    patience: 5,
    verdict: '',
    mfe: '',
    mae: '',
    missedR: '',
    actualR: '',
    insight: '',
    patternInsight: '',
    linkedPlaybook: '',
    linkedLabDate: null,
    replayStep: 0,
    mode: REPLAY_MODES.trade,
    scenarioType: '',
    replayStatus: REPLAY_STATUSES.draft,
    playbackSpeedMs: 2500,
    replayDate: null,
    sourceDate: null,
    notes: '',
    emotionalState: '',
    whatISaw: '',
    whatIMissed: '',
    improvementPlan: '',
    lessonSummary: '',
    ruleFollowed: '',
    reviewBiggestMistake: '',
    reviewBestMoment: '',
    tradeRef: '',
    completedAt: null,
    pnl: '',
    autoFocusNotes: true,
    showLessons: true,
    learningExample: false,
    learningExampleKind: null,
    replayMarkers: [],
    ...overrides,
  };
}
